export const PRIORITY = Object.freeze({
  P0: 'P0',
  P1: 'P1',
  P2: 'P2',
  VNEXT: 'VNEXT',
});

export const MATURITY = Object.freeze({
  REUSE_AS_IS: 'REUSE_AS_IS',
  REUSE_WITH_ADAPTER: 'REUSE_WITH_ADAPTER',
  HARDEN: 'HARDEN',
  REFACTOR: 'REFACTOR',
  IMPLEMENTED_FOUNDATION: 'IMPLEMENTED_FOUNDATION',
  SPECIFIED_NEXT: 'SPECIFIED_NEXT',
  BLOCKED_SOURCE: 'BLOCKED_SOURCE',
  FUTURE_VISION: 'FUTURE_VISION',
});

export const DATA_STATE = Object.freeze({
  LIVE: 'LIVE',
  DEGRADED: 'DEGRADED',
  STALE: 'STALE',
  UNAVAILABLE: 'UNAVAILABLE',
});

export const EVIDENCE_KIND = Object.freeze({
  OFFICIAL_OBSERVATION: 'OFFICIAL_OBSERVATION',
  OFFICIAL_FORECAST: 'OFFICIAL_FORECAST',
  OFFICIAL_WARNING: 'OFFICIAL_WARNING',
  PROVIDER_FORECAST: 'PROVIDER_FORECAST',
  EARTHUS_ANALYSIS: 'EARTHUS_ANALYSIS',
  EARTHUS_FORECAST: 'EARTHUS_FORECAST',
  ESTIMATED_DISTRIBUTION: 'ESTIMATED_DISTRIBUTION',
  SIMULATION: 'SIMULATION',
  HISTORY: 'HISTORY',
  VISUALIZATION_ONLY: 'VISUALIZATION_ONLY',
});

export const ACCESS_TIER = Object.freeze({
  FREE: 'FREE',
  PLUS: 'PLUS',
  CONTROL: 'CONTROL',
  BUSINESS: 'BUSINESS',
});

export const SCENE_MODE = Object.freeze({
  LAND: 'LAND',
  URBAN: 'URBAN',
  OCEAN: 'OCEAN',
  ATMOSPHERE: 'ATMOSPHERE',
  EVENT: 'EVENT',
  SPACE: 'SPACE',
});

export const VISUAL_ENGINE = Object.freeze({
  TOWER: 'TOWER',
  RELIEF: 'RELIEF',
  FIELD: 'FIELD',
  FLOW: 'FLOW',
  NETWORK: 'NETWORK',
  VOLUME: 'VOLUME',
  PULSE: 'PULSE',
  TRACK: 'TRACK',
  BEACON: 'BEACON',
});

export const TIME_MODE = Object.freeze({
  LIVE: 'LIVE',
  FORECAST: 'FORECAST',
  HISTORY: 'HISTORY',
  SCENARIO: 'SCENARIO',
});

export const THERMAL_STATE = Object.freeze({
  NORMAL: 'NORMAL',
  BALANCED: 'BALANCED',
  ECO: 'ECO',
  SAFE: 'SAFE',
});

export const ENGINE_LIFECYCLE = Object.freeze({
  REGISTERED: 'REGISTERED',
  MOUNTING: 'MOUNTING',
  READY: 'READY',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DISPOSING: 'DISPOSING',
  DISPOSED: 'DISPOSED',
  ERROR: 'ERROR',
});

export const MODEL_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SHADOW: 'SHADOW',
  CANARY: 'CANARY',
  ACTIVE: 'ACTIVE',
  ROLLBACK: 'ROLLBACK',
  RETIRED: 'RETIRED',
});

export const ARCHIVE_STATE = Object.freeze({
  HOT: 'HOT',
  PACKING: 'PACKING',
  COPY_PENDING: 'COPY_PENDING',
  COPYING: 'COPYING',
  VERIFYING: 'VERIFYING',
  NAS_VERIFIED: 'NAS_VERIFIED',
  SNAPSHOT_VERIFIED: 'SNAPSHOT_VERIFIED',
  GRACE_PERIOD: 'GRACE_PERIOD',
  DELETE_ELIGIBLE: 'DELETE_ELIGIBLE',
  COLD_ARCHIVED: 'COLD_ARCHIVED',
  RESTORE_PENDING: 'RESTORE_PENDING',
  RESTORING: 'RESTORING',
  RESTORED_HOT: 'RESTORED_HOT',
  NAS_UNAVAILABLE: 'NAS_UNAVAILABLE',
  COPY_FAILED: 'COPY_FAILED',
  CHECKSUM_FAILED: 'CHECKSUM_FAILED',
  MANIFEST_MISMATCH: 'MANIFEST_MISMATCH',
  SNAPSHOT_FAILED: 'SNAPSHOT_FAILED',
  DELETE_BLOCKED: 'DELETE_BLOCKED',
  RESTORE_FAILED: 'RESTORE_FAILED',
});

export const TRUTH_FIDELITY = Object.freeze({
  NONE: 'NONE',
  SUMMARY: 'SUMMARY',
  AGGREGATE: 'AGGREGATE',
  GRID: 'GRID',
  GEOMETRY: 'GEOMETRY',
  PROBABILISTIC_VOLUME: 'PROBABILISTIC_VOLUME',
  PRECISION: 'PRECISION',
});

export const REGION_STANDARD = Object.freeze({
  KR: 'KR',
  JP: 'JP',
  US: 'US',
  GB: 'GB',
  GLOBAL: 'GLOBAL',
});

export const ENGINE_CLASS = Object.freeze({
  DYNAMIC: 'DYNAMIC',
  STATIC_CONTEXT: 'STATIC_CONTEXT',
  ORCHESTRATOR: 'ORCHESTRATOR',
  NON_VISUAL: 'NON_VISUAL',
});
