import fs from 'node:fs';
import path from 'node:path';
import {EarthusUIAdapterV36} from '../core/EARTHUS_UI_ADAPTER_V36.mjs';
import {STATES} from '../../06_BUNDLED_DATA_PACKAGE/pleos_safety_v33/PLEOS_SAFETY_GATE_V33.mjs';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../..');
const d=path.join(root,'06_BUNDLED_DATA_PACKAGE');
const master=JSON.parse(fs.readFileSync(path.join(d,'spatial_v24/POI_MASTER.json'),'utf8'));
const index=JSON.parse(fs.readFileSync(path.join(d,'spatial_v24/SPATIAL_GRID_INDEX.json'),'utf8'));
const app=new EarthusUIAdapterV36({poiMaster:master,spatialIndex:index,drivingStateProvider:()=>STATES.PARKED,repository:{getEnvironment:async()=>({weather:{temperature:21},observedAt:'2026-09-25T00:00:00Z'})}});
app.app.setMapState({bbox:[128.9,35.0,129.1,35.2],layers:['weather']});
app.openDock('local');
const q=await app.app.queryLocalPois({bbox:[128.9,35.0,129.1,35.2]});
const poi=q.items[0]||master[0];
await app.selectPoi(poi);
const selected=app.view().selectedPoiId;
app.openDock('weather');
if(app.view().selectedPoiId!==selected || app.view().mapBbox.join(',')!=='128.9,35,129.1,35.2') throw new Error('state persistence failed');
app.setDrivingStateProvider(()=>STATES.DRIVING);
if(app.action('reservation').allowed) throw new Error('reservation executable while driving');
if(!app.action('weather').allowed) throw new Error('weather should remain allowed while driving');
console.log(JSON.stringify({status:'PASS',journey:['Dock','Panel','Map','POI','PlaceCard','Dock switch','Driving Safety'],selectedPoi:selected,safety:'PASS'}));
