import test from 'node:test';import assert from 'node:assert/strict';import {evaluateClaim,claimLabel,normalizeExplicitContext,mapKtoSignalToFeature,mapKmaWeatherToFeature,mapAirKoreaToPollution,mapFirmsToFire,jobsForTrigger,travelPilotMetrics,environmentLearningMetrics,traceabilityMetrics,validateQuery,intelligenceHealth,shadowRecord,sourceEligibleForUse} from '../../prototype/js/earthus2/v11/index.js';
test('claim gate blocks pollution attribution without explicit attribution evidence',()=>assert.equal(evaluateClaim('SOURCE_ATTRIBUTION',{}).allowed,false));
test('transport claim labels modelled only with proof',()=>assert.equal(claimLabel('TRANSPORT',{vectorProof:true,transportEvidenceKind:'MODELLED'}),'MODELLED_TRANSPORT'));
test('explicit context drops unknown kinds',()=>{const x=normalizeExplicitContext([{kind:'SAVED_PLACE',subjectId:'a'},{kind:'HEALTH',subjectId:'x'}]);assert.deepEqual(x.savedPlaceIds,['a']);assert.equal(Object.hasOwn(x,'health'),false);});
test('KTO feature mapper refuses missing observation time',()=>assert.equal(mapKtoSignalToFeature({placeId:'p',metric:'demand',normalizedValue:.5}),null));
test('KMA mapper preserves official forecast evidence class',()=>assert.equal(mapKmaWeatherToFeature({placeId:'p',suitability:.8,issuedAt:'2026-08-26T00:00Z'}).evidenceKind,'OFFICIAL_FORECAST'));
test('AirKorea mapper returns observed pollution',()=>assert.equal(mapAirKoreaToPollution({stationId:'s',sourceId:'AirKorea',observedAt:'2026-08-26T00:00Z',pollutant:'PM2.5',value:10}).evidenceKind,'OBSERVED'));
test('FIRMS mapper is detected not observed ground truth',()=>assert.equal(mapFirmsToFire({hotspotId:'h',sourceId:'FIRMS',observedAt:'2026-08-26T00:00Z'}).evidenceKind,'DETECTED'));
test('jobs are shadow by default',()=>assert.ok(jobsForTrigger('KTO_OR_KMA_UPDATE').every(x=>x.mode==='SHADOW')));
test('travel pilot metrics do not fabricate without sessions',()=>assert.equal(travelPilotMetrics([]).meanDecisionSeconds,null));
test('environment learning uses real paired scores only',()=>assert.equal(environmentLearningMetrics([{preScore:2,postScore:4}]).meanGain,2));
test('traceability metric uses shown outputs denominator',()=>assert.equal(traceabilityMetrics([{outputShown:true,sourceVisible:true,truthLabelVisible:false}]).sourceVisibleRate,1));
test('query validator clamps limit',()=>assert.equal(validateQuery({limit:500}).query.limit,200));
test('query validator rejects invalid bbox',()=>assert.equal(validateQuery({bbox:[20,10,10,30]}).ok,false));
test('intelligence health is degraded with one blocked capability',()=>assert.equal(intelligenceHealth([{releaseState:'SHADOW',providerHealthy:true},{releaseState:'SHADOW',providerHealthy:false}]).state,'DEGRADED'));
test('shadow materializer requires provenance',()=>assert.equal(shadowRecord('X',{},{}).accepted,false));
test('shadow materializer cannot accidentally emit ACTIVE',()=>assert.equal(shadowRecord('X',{}, {sourceIds:['KTO']}).record.releaseState,'SHADOW'));
test('source use requires approved rights',()=>assert.equal(sourceEligibleForUse({rightsState:'DRAFT',allowedUses:['PUBLIC_DERIVED']},'PUBLIC_DERIVED').allowed,false));
test('source use requires exact allowed mode',()=>assert.equal(sourceEligibleForUse({rightsState:'APPROVED',allowedUses:['INTERNAL_DERIVED']},'PUBLIC_DERIVED').reason,'USE_NOT_ALLOWED'));
