const URLS={daily:'/wind/series/verify-daily.json',cases:'/wind/series/verify-cases.json',stations:'/wind/series/stations.json'};const $=s=>document.querySelector(s);const state={};
const esc=v=>{const s=v==null?'':String(v);return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s};
function download(name,headers,rows){const csv='\ufeff'+[headers,...rows].map(row=>row.map(esc).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function json(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${url} HTTP ${r.status}`);return r.json()}
function latest(index){const days=Object.keys(index?.dates||{}).sort();return days.length?days.at(-1):null}
async function loadLatest(index){const day=latest(index);if(!day)return null;return json(index.dates[day].path)}
function pack(title,tag,description,meta,onClick,enabled=true){const el=document.createElement('article');el.className='pack';el.innerHTML=`<span class="tag">${tag}</span><h2>${title}</h2><p>${description}</p><dl>${meta.map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('')}</dl>`;const b=document.createElement('button');b.textContent=enabled?'CSV 내려받기':'자료 없음';b.disabled=!enabled;if(enabled)b.onclick=onClick;el.append(b);return el}
function dailyRows(){const rows=[];Object.entries(state.daily.days||{}).forEach(([day,records])=>Object.entries(records).forEach(([key,v])=>{const [model,variable,lead]=key.split('|');rows.push([day,model,variable,lead,v.me,v.mae,v.rmse,v.n,state.daily.leadBasis,state.daily.source,state.daily.generated])}));return rows}
function stationRows(){const rows=[];Object.entries(state.stationDay?.hours||{}).forEach(([time,hour])=>(hour.stations||[]).forEach(item=>{const m=state.stationDay.stationMeta?.[item.stationId]||{};const v=item.values||{};rows.push([time,item.stationId,m.name,m.lat,m.lon,m.alt,v.temp_c,v.humid_pct,v.wind_ms,v.wind_dir,v.rain_mm,v.pres_hpa,v.pres_sea,v.dewp_c,v.solar,v.cloud,state.stationDay.source,state.stationDay.generated])}));return rows}
function caseRows(){const rows=[];Object.entries(state.caseDay?.hours||{}).forEach(([time,hour])=>(hour.cases||[]).forEach(item=>Object.entries(item.forecasts||{}).forEach(([model,leads])=>Object.entries(leads).forEach(([lead,vars])=>Object.entries(vars).forEach(([variable,forecast])=>{const obs=item.observation?.[variable];rows.push([time,item.stationId,model,lead,variable,obs,forecast,Number.isFinite(Number(obs))?forecast-obs:null,hour.issues?.[lead],state.caseDay.source,state.caseDay.generated])})))));return rows}
function render(){const packs=$('#packs');packs.innerHTML='';const dr=dailyRows(),sr=stationRows(),cr=caseRows();packs.append(pack('일별 예보 검증','DAILY SCORES','모델·변수·선행시간별 ME·MAE·RMSE와 표본 수 n.',[['기간',`${state.daily.collectingSince} → ${Object.keys(state.daily.days||{}).sort().at(-1)}`],['행',dr.length],['기준',state.daily.leadBasis]],()=>download('earthus-forecast-daily.csv',['date','model','variable','lead','me','mae','rmse','n','lead_basis','source','generated'],dr),dr.length>0));packs.append(pack('ASOS 시간 관측','STATION HOURS','지점별 시간 관측과 좌표·해발고도. 결측 열은 빈칸.',[['날짜',state.stationDay?.date||'없음'],['시각',state.stationDay?.hourCount||0],['행',sr.length]],()=>download(`earthus-asos-${state.stationDay.date}.csv`,['observed_kst','station_id','station_name','lat','lon','alt_m','temp_c','humidity_pct','wind_ms','wind_dir_deg','rain_mm','pressure_hpa','sea_pressure_hpa','dewpoint_c','solar','cloud_tenths','source','generated'],sr),sr.length>0));packs.append(pack('예보·관측 사례','STATION CASES','한 지점·한 시각의 관측, 모델 예보, 예보−관측 차이.',[['날짜',state.caseDay?.date||'없음'],['시각',state.caseDay?.hourCount||0],['행',cr.length]],()=>download(`earthus-forecast-cases-${state.caseDay.date}.csv`,['valid_kst','station_id','model','lead','variable','observation','forecast','forecast_minus_observation','issued_kst','source','generated'],cr),cr.length>0));$('#scope').textContent=`일별 집계 ${state.daily.count}일 · ASOS ${state.stationDay?.hourCount||0}시각/${state.stationDay?.rowCount||0}행 · 사례 ${state.caseDay?.hourCount||0}시각/${cr.length}행`;$('#generated').textContent=`최신 생성 · ${state.daily.generated} · CSV는 브라우저에서 현재 공개 JSON을 변환`}
async function boot(){try{[state.daily,state.caseIndex,state.stationIndex]=await Promise.all([json(URLS.daily),json(URLS.cases),json(URLS.stations)]);[state.caseDay,state.stationDay]=await Promise.all([loadLatest(state.caseIndex),loadLatest(state.stationIndex)]);render()}catch(e){$('#error').hidden=false;$('#error').textContent=`Research Pack 자료를 읽지 못했습니다. (${e.message})`}}boot();
