import test from 'node:test'; import assert from 'node:assert/strict';
import { minimizePersonalContext } from '../../prototype/js/earthus2/v04/paid/personal-context.js';
import { compareNormalized } from '../../prototype/js/earthus2/v04/paid/comparison.js';
import { scenarioExecutionGate } from '../../prototype/js/earthus2/v04/paid/scenario.js';
import { transitionSubscription } from '../../prototype/js/earthus2/v04/paid/subscription-state.js';
import { premiumCacheKey, PremiumCache } from '../../prototype/js/earthus2/v04/paid/premium-cache.js';
import { buildArchivePackagePlan } from '../../prototype/js/earthus2/v04/storage/archive-packager.js';
import { NasArchiveAgentState } from '../../prototype/js/earthus2/v04/storage/nas-archive-agent.js';
import { ArchiveCatalog } from '../../prototype/js/earthus2/v04/storage/archive-catalog.js';
import { compileWeatherDetailSections } from '../../prototype/js/earthus2/v04/weather/weather-detail-ia.js';
import { detectWeatherEvents } from '../../prototype/js/earthus2/v04/weather/weather-event-detector.js';
import { evaluateCycloneRemnantInteraction } from '../../prototype/js/earthus2/v04/weather/cyclone-remnant-interaction.js';
import { weatherActionDecision } from '../../prototype/js/earthus2/v04/weather/weather-action-intelligence.js';
import { weatherForecastMetrics, weatherModelPromotionGate } from '../../prototype/js/earthus2/v04/weather/weather-modelops.js';

test('personal context drops secret fields',()=>assert.equal(minimizePersonalContext({savedPlaceIds:['x'],email:'a@b.c'},{consent:true}).context.email,undefined));
test('comparison blocks units mismatch',()=>assert.equal(compareNormalized([{variable:'t',unit:'C',value:1},{variable:'t',unit:'F',value:2}]).state,'BLOCKED'));
test('scenario requires control',()=>assert.equal(scenarioExecutionGate({plan:'PLUS',quotaRemaining:5}).allowed,false));
test('subscription invalid transition blocks',()=>assert.equal(transitionSubscription('FREE','CANCEL').allowed,false));
test('premium cache key stable',()=>assert.equal(premiumCacheKey({feature:'WHY',context:{a:1}}),premiumCacheKey({feature:'WHY',context:{a:1}})));
test('premium cache expires',()=>{const c=new PremiumCache();c.put('x',{v:1},{ttlSec:1,nowMs:0});assert.equal(c.get('x',{nowMs:2000}),null);});
test('archive plan is no direct nas serving',()=>assert.equal(buildArchivePackagePlan({datasetId:'cloud',region:'asia',startAt:'2026-01-01T00:00:00Z',endAt:'2026-01-01T01:00:00Z',logicalRecords:10,schemaVersion:'1',processorVersion:'1'}).directNasServing,false));
test('nas agent reaches verified state',()=>{const a=new NasArchiveAgentState();a.enqueue({archiveId:'a',sourcePrefix:'s3://x'});a.update('a','START');a.update('a','VERIFY');assert.equal(a.update('a','VERIFIED').state,'NAS_VERIFIED');});
test('archive catalog finds time',()=>{const c=new ArchiveCatalog();c.register({archiveId:'a',datasetId:'cloud',region:'asia',startAt:'2026-01-01T00:00:00Z',endAt:'2026-01-02T00:00:00Z'});assert.equal(c.find({at:'2026-01-01T12:00:00Z'}).length,1);});
test('free weather deep analysis is preview',()=>assert.equal(compileWeatherDetailSections(['DEEP_ANALYSIS'],{plan:'FREE'}).find(x=>x.id==='DEEP_ANALYSIS').access,'PREVIEW'));
test('weather detector is not official warning',()=>assert.equal(detectWeatherEvents({precipRateMmH:40}).officialWarning,false));
test('cyclone causal claim requires strong multi signal',()=>assert.equal(evaluateCycloneRemnantInteraction({remnantDistanceKm:100,moistureTransport:.9,frontOverlap:true,upperJetSupport:true,verticalMotion:.9}).causalClaimAllowed,true));
test('official gate blocks weather action',()=>assert.equal(weatherActionDecision({officialGates:[{level:'WARNING'}],windows:[{score:1,confidence:1}]}).state,'BLOCKED_BY_OFFICIAL_GATE'));
test('weather metrics calculate mae',()=>assert.equal(weatherForecastMetrics([{predicted:2,actual:1},{predicted:4,actual:2}]).mae,1.5));
test('weather promotion needs rollback',()=>assert.equal(weatherModelPromotionGate({shadowMetrics:{count:40,mae:1},activeMetrics:{mae:2},calibrationPass:true,rollbackReady:false}).pass,false));
