-- EARTHUS 2.0 Advanced Intelligence Backend v1.0
-- ADDITIVE CONTRACT ONLY. Review against live Supabase migrations before applying.
-- No fabricated rows, no default scores, and no automatic ACTIVE promotion.

create table if not exists public.earthus_intelligence_feature_value (
  id bigint generated by default as identity primary key,
  feature_value_id text not null unique,
  subject_id text not null,
  feature_key text not null,
  value_json jsonb not null,
  unit text,
  source_id text not null,
  evidence_kind text not null,
  observed_at timestamptz not null,
  valid_at timestamptz not null,
  confidence double precision not null check (confidence between 0 and 1),
  data_state text not null,
  release_state text not null default 'SHADOW',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists eifv_subject_feature_valid_idx on public.earthus_intelligence_feature_value(subject_id,feature_key,valid_at desc);

create table if not exists public.earthus_evidence_node (
  evidence_id text primary key, evidence_kind text not null, source_id text not null,
  external_id text, title text, observed_at timestamptz, source_url text,
  payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.earthus_evidence_edge (
  id bigint generated by default as identity primary key,
  from_evidence_id text not null references public.earthus_evidence_node(evidence_id) on delete cascade,
  to_evidence_id text not null references public.earthus_evidence_node(evidence_id) on delete cascade,
  relation text not null, metadata jsonb not null default '{}'::jsonb,
  unique(from_evidence_id,to_evidence_id,relation)
);

create table if not exists public.earthus_event_cluster (
  event_id text primary key, event_type text not null, title text,
  started_at timestamptz, updated_at timestamptz not null default now(),
  country text, region text, latitude double precision, longitude double precision,
  status text not null default 'UNKNOWN', official_safety boolean not null default false,
  confidence double precision check (confidence between 0 and 1),
  release_state text not null default 'SHADOW', payload jsonb not null default '{}'::jsonb
);
create index if not exists eec_type_time_idx on public.earthus_event_cluster(event_type,started_at desc);
create table if not exists public.earthus_event_cluster_member (
  event_id text not null references public.earthus_event_cluster(event_id) on delete cascade,
  member_id text not null, member_kind text not null, source_id text,
  evidence_id text references public.earthus_evidence_node(evidence_id),
  payload jsonb not null default '{}'::jsonb, primary key(event_id,member_id)
);

create table if not exists public.earthus_travel_discovery_result (
  id bigint generated by default as identity primary key,
  place_id text not null, computed_at timestamptz not null default now(),
  score double precision check (score between 0 and 1), eligible boolean not null,
  reason text, components jsonb not null default '{}'::jsonb, evidence jsonb not null default '{}'::jsonb,
  release_state text not null default 'SHADOW'
);
create index if not exists etdr_place_time_idx on public.earthus_travel_discovery_result(place_id,computed_at desc);
create table if not exists public.earthus_travel_best_window (
  id bigint generated by default as identity primary key, place_id text not null,
  starts_at timestamptz not null, ends_at timestamptz not null, score double precision,
  eligible boolean not null, reason text, evidence jsonb not null default '{}'::jsonb,
  release_state text not null default 'SHADOW'
);

create table if not exists public.earthus_pollution_event (
  pollution_event_id text primary key, domain text not null, pollutant text,
  started_at timestamptz, source_attribution_status text not null default 'SOURCE_NOT_ATTRIBUTED',
  evidence jsonb not null default '[]'::jsonb, release_state text not null default 'SHADOW',
  created_at timestamptz not null default now()
);
create table if not exists public.earthus_pollution_transport_run (
  transport_run_id text primary key, pollution_event_id text not null references public.earthus_pollution_event(pollution_event_id) on delete cascade,
  vector_source_id text not null, vector_kind text not null, started_at timestamptz not null,
  trajectory jsonb not null, evidence_kind text not null default 'MODELLED',
  source_attribution_status text not null default 'SOURCE_NOT_ATTRIBUTED',
  release_state text not null default 'SHADOW', created_at timestamptz not null default now()
);

create table if not exists public.earthus_public_action_event (
  action_id text primary key, organization text not null, title text not null,
  activity_type text not null, status text not null, starts_at timestamptz, ends_at timestamptz,
  country text, region text, city text, location_precision text not null,
  latitude double precision, longitude double precision,
  official_source_url text not null, participation_url text,
  topics jsonb not null default '[]'::jsonb, updated_at timestamptz not null default now()
);

create table if not exists public.earthus_memory_signature (
  event_id text primary key, event_type text not null, observed_at timestamptz,
  region text, numeric_features jsonb not null default '{}'::jsonb,
  categorical_features jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.earthus_memory_match (
  target_event_id text not null, analog_event_id text not null,
  distance double precision not null, common_features integer not null,
  computed_at timestamptz not null default now(),
  primary key(target_event_id,analog_event_id)
);

create table if not exists public.earthus_intelligence_model (
  model_key text primary key, model_id text not null, version text not null,
  state text not null default 'DRAFT', metrics jsonb, evidence jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(), unique(model_id,version)
);
create table if not exists public.earthus_forecast_ground_truth (
  id bigint generated by default as identity primary key,
  prediction_id text not null, subject_id text not null, metric text not null,
  target_at timestamptz not null, observed_at timestamptz not null,
  predicted_value double precision not null, actual_value double precision not null,
  error double precision not null, model_key text, created_at timestamptz not null default now()
);
create index if not exists efgt_model_metric_idx on public.earthus_forecast_ground_truth(model_key,metric,target_at desc);
create table if not exists public.earthus_calibration_metric (
  id bigint generated by default as identity primary key,
  model_key text not null, metric text not null, region text, horizon_minutes integer,
  sample_count integer not null, mae double precision, bias double precision, rmse double precision,
  measured_at timestamptz not null default now()
);

create table if not exists public.earthus_intelligence_release (
  capability text not null, version text not null, state text not null default 'SHADOW',
  evidence jsonb not null default '{}'::jsonb, approved_at timestamptz,
  created_at timestamptz not null default now(), primary key(capability,version)
);

-- Explicit user context only; never infer sensitive traits. RLS is mandatory.
create table if not exists public.earthus_user_context_v2 (
  user_id uuid not null, context_kind text not null, subject_id text not null,
  payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(), primary key(user_id,context_kind,subject_id)
);
alter table public.earthus_user_context_v2 enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='earthus_user_context_v2' and policyname='earthus_user_context_v2_owner') then
    create policy earthus_user_context_v2_owner on public.earthus_user_context_v2
      for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
  end if;
end $$;


create table if not exists public.earthus_intelligence_pilot_measurement (
  id bigint generated by default as identity primary key,
  pilot_id text not null, domain text not null, metric text not null,
  value double precision, numerator double precision, denominator double precision,
  sample_count integer, measured_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists eipm_pilot_metric_idx on public.earthus_intelligence_pilot_measurement(pilot_id,domain,metric,measured_at desc);

create table if not exists public.earthus_intelligence_release_audit (
  id bigint generated by default as identity primary key,
  capability text not null, version text not null, from_state text, to_state text not null,
  gate_result jsonb not null, actor text, changed_at timestamptz not null default now()
);
