// Run against a local research-runtime server; writes only test projects and evidence.
// RESEARCH_UI_URL=http://127.0.0.1:8789/v2-three/research.html node tools/research/test-ui.mjs
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';
import { wrapLongitude, visibleSample, normalizeResult } from '../../prototype/v2-three/js/research/result-layer.js';

assert.equal(wrapLongitude(181), -179);
assert.equal(wrapLongitude(-181), 179);
assert.equal(visibleSample([{ timeUTC: '2025-01-01T01:00:00Z', lon: 1, lat: 0 }], Date.parse('2025-01-01T00:00:00Z')), null, 'Do not show future particle positions.');
assert.equal(normalizeResult({ trajectories: [{ samples: [{ timeUTC: 'invalid', lon: 1, lat: 2 }] }] }).trajectories[0].samples.length, 0);

const url = process.env.RESEARCH_UI_URL || 'http://127.0.0.1:8789/v2-three/research.html';
const evidence = path.resolve('docs/research/evidence');
await fs.mkdir(evidence, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const checks = [];
try {
  await page.goto(url);
  await page.locator('#backend-status.online').waitFor();
  await page.screenshot({ path: path.join(evidence, 'ui-projects-desktop.png'), fullPage: true });
  const projectName = `UI ${Date.now()} <img src=x onerror=alert(1)>`;
  await page.locator('#project-name').fill(projectName);
  await page.locator('#project-question-input').fill('합성 동향 흐름에서 기준 위치와 대안 방출 위치의 차이를 재현할 수 있는가?');
  await page.locator('#project-form button[type=submit]').click();
  await page.locator('#page-datasets').waitFor({ state: 'visible' });
  await page.locator('#dataset-list .item').filter({ hasText: '합성 수치시험' }).first().click();
  await page.locator('#dataset-details').getByText('합성 수치시험', { exact: true }).waitFor();
  await page.locator('#use-dataset').click();
  await page.locator('#page-experiments').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#current-project img').count(), 0, 'User title must remain text.');
  assert.equal(await page.locator('#submit-run').isDisabled(), true, 'Run is gated before preflight.');
  checks.push('project creation, dataset inspection, XSS-safe user title, preflight gate');
  async function submitExperiment(name, lon) {
    await page.locator('#experiment-name').fill(name);
    await page.locator('#duration').fill('2');
    await page.locator('#particle-count').fill('2');
    await page.locator('#release-lon').fill(String(lon));
    await page.locator('#experiment-form button[type=submit]').click();
    await page.locator('#preflight').waitFor({ state: 'visible' });
    await page.waitForFunction(() => !document.getElementById('preflight').disabled);
    await page.locator('#preflight').click();
    await page.waitForFunction(() => !document.getElementById('submit-run').disabled, undefined, { timeout: 60000 });
    await page.locator('#submit-run').click();
    await page.locator('#page-runs').waitFor({ state: 'visible' });
    await page.waitForFunction(() => !document.getElementById('view-results').disabled, undefined, { timeout: 90000 });
    const runId = await page.locator('#run-details dd').first().textContent();
    await page.locator('#view-results').click();
    await page.locator('#page-results').waitFor({ state: 'visible' });
    await page.locator('#result-status').getByText('COMPLETE', { exact: false }).waitFor();
    return runId;
  }
  const baselineId = await submitExperiment('UI baseline', 0);
  await page.screenshot({ path: path.join(evidence, 'ui-results-desktop.png'), fullPage: true });
  await page.locator('#view-3d').click();
  await page.locator('#globe-host canvas').waitFor();
  await page.locator('#map-status').getByText('참조 지형 로드됨.').waitFor();
  await page.screenshot({ path: path.join(evidence, 'ui-globe-desktop.png'), fullPage: true });
  assert.equal(await page.locator('#view-3d').getAttribute('aria-pressed'), 'true');
  await page.locator('#view-2d').click();
  await page.locator('#fit-input').click();
  assert.equal(await page.locator('#fit-input').getAttribute('aria-pressed'), 'true');
  await page.screenshot({ path: path.join(evidence, 'ui-input-region-desktop.png'), fullPage: true });
  await page.locator('#fit-trajectory').click();
  await page.locator('#result-time').fill('0');
  assert.match(await page.locator('#time-label').textContent(), /2025-01-01T00:00:00 UTC/);
  checks.push('saved experiment, preflight, actual run completion, trajectories, shared timeline, Three.js globe');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export-link').click();
  const download = await downloadPromise;
  await download.saveAs(path.join(evidence, 'ui-baseline-export.zip'));
  checks.push('reproduction ZIP downloaded');
  await page.locator('[data-page=experiments]').click();
  const comparisonId = await submitExperiment('UI alternative release', 0.1);
  await page.locator('#result-run').selectOption(baselineId);
  await page.locator('#comparison-run').selectOption(comparisonId);
  await page.locator('#compare').click();
  await page.locator('#comparison-metrics details').waitFor();
  assert.match(await page.locator('#comparison-metrics').textContent(), /comparison|distribution|paired|separation|difference/i);
  checks.push('two actual runs compared');
  await page.screenshot({ path: path.join(evidence, 'ui-comparison-desktop.png'), fullPage: true });
  await page.locator('[data-page=experiments]').click();
  await page.locator('#experiment-name').fill('UI cancellation');
  await page.locator('#duration').fill('72');
  await page.locator('#particle-count').fill('1000');
  await page.locator('#experiment-form button[type=submit]').click();
  await page.waitForFunction(() => !document.getElementById('preflight').disabled);
  await page.locator('#preflight').click();
  await page.waitForFunction(() => !document.getElementById('submit-run').disabled);
  await page.locator('#submit-run').click();
  await page.locator('#page-runs').waitFor({ state: 'visible' });
  await page.locator('#cancel-run').click();
  await page.waitForFunction(() => document.getElementById('run-details').textContent.includes('취소됨'), undefined, { timeout: 30000 });
  assert.equal(await page.locator('#view-results').isDisabled(), true);
  checks.push('actual submitted computation cancelled; cancelled result unavailable');
  await page.locator('[data-page=experiments]').click();
  await page.locator('#experiment-name').fill('UI invalid coverage');
  await page.locator('#start-time').fill('2025-01-04T00:00');
  await page.locator('#experiment-form button[type=submit]').click();
  await page.waitForFunction(() => !document.getElementById('preflight').disabled);
  await page.locator('#preflight').click();
  await page.locator('#preflight-summary').getByText('실행할 수 없습니다.', { exact: false }).waitFor();
  assert.equal(await page.locator('#submit-run').isDisabled(), true);
  checks.push('insufficient forcing time coverage rejects actual preflight');
  await page.reload();
  await page.locator('#backend-status.online').waitFor();
  assert.equal(await page.locator('#result-run option').count() >= 3, true);
  checks.push('server records survive reload');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('[data-page=projects]').click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile has no page overflow.');
  await page.screenshot({ path: path.join(evidence, 'ui-projects-mobile.png'), fullPage: true });
  await page.locator('[data-page=results]').click();
  await page.locator('#result-run').selectOption(baselineId);
  await page.locator('#comparison-run').selectOption('');
  await page.locator('#load-result').click();
  await page.locator('#result-status').getByText('COMPLETE', { exact: false }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: path.join(evidence, 'ui-results-mobile.png'), fullPage: true });
  checks.push('390px mobile layout without overflow');
  await page.route('**/api/research/**', route => route.abort());
  await page.locator('#refresh').click();
  await page.locator('#backend-status').getByText('계산 서비스 연결 안 됨').waitFor();
  assert.equal(await page.locator('#load-result').isDisabled(), true);
  checks.push('backend failure shown honestly; online action disabled');
  assert.deepEqual(errors, [], 'No uncaught browser errors.');
  await fs.writeFile(path.join(evidence, 'ui-checks.json'), JSON.stringify({ verifiedAtUTC: new Date().toISOString(), url, browser: 'Microsoft Edge (Playwright)', checks, baselineId, comparisonId, uncaughtErrors: errors }, null, 2));
  console.log(JSON.stringify({ ok: true, checks, baselineId, comparisonId }, null, 2));
} catch (error) {
  await page.screenshot({ path: path.join(evidence, 'ui-failure.png'), fullPage: true });
  console.error(await page.locator('body').innerText());
  throw error;
} finally { await browser.close(); }
