const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const state={mode:'SPACE',universe:null,data:null,envelope:null,scene:null,aux:{},globalIntel:[],explanation:null,primaryDataStatus:'UNAVAILABLE',selectedScale:'SOLAR_SYSTEM_VIEW',labels:true,grid:true};
const modeMeta={
  SPACE:{index:'01',title:'SOLAR SYSTEM',subtitle:'SOLAR SYSTEM EPHEMERIS · MULTI-SCALE SPACE',caption:'From Earth to the solar system — one continuous universe.'},
  CONTROL:{index:'02',title:'MISSION CONTROL',subtitle:'MISSION LIFECYCLE · OFFICIAL / MODELLED SEPARATION',caption:'Mission state, trajectory and evidence — never mixed.'},
  ORBIT:{index:'03',title:'ORBITAL ENVIRONMENT',subtitle:'LEO / MEO / GEO · SEMANTIC LOD · CONJUNCTION',caption:"Don't show every object. Show what matters."},
  INTELLIGENCE:{index:'04',title:'INTELLIGENCE CORE',subtitle:'EVIDENCE → SIGNAL → EVENT → REVISION → DECISION',caption:'Why it matters, how certain it is, and what changed.'},
  ARCHIVE:{index:'05',title:'TIME MACHINE / ARCHIVE',subtitle:'APPEND-ONLY HISTORY · ARCHIVED ≠ RECONSTRUCTED',caption:'Past state stays traceable. Reconstructed state stays labelled.'}
};
let visual;
const t=(key,fallback='')=>window.AetherusI18n?.t(key,fallback)??fallback??key;
function currentModeMeta(mode){const base=modeMeta[mode];return {...base,title:t(`mode.${mode}.title`,base.title),subtitle:t(`mode.${mode}.subtitle`,base.subtitle),caption:t(`mode.${mode}.caption`,base.caption)}}
function applyLocale(){window.AetherusI18n?.apply();const m=currentModeMeta(state.mode),ko=window.AetherusI18n?.locale==='ko';$('#contextTitle').textContent=m.title;$('#contextSubtitle').textContent=m.subtitle;$('#captionText').textContent=m.caption;$('#modeTitle').textContent=ko?t(`nav.${state.mode.toLowerCase()}`,state.mode):state.mode;$('#timeModeLabel').textContent=state.universe?.time_mode==='NOW'?t('universal.now','UNIVERSAL NOW'):String(state.universe?.time_mode||'NOW').replaceAll('_',' ');$('#scientificWarning').textContent=(state.data||{}).warning||state.envelope?.warnings?.[0]||scientificWarning(state.mode,state.primaryDataStatus);document.title=ko?'AETHERUS V2 — 우주 인텔리전스 & 비주얼 OS':'AETHERUS V2 — Space Intelligence & Visual OS'}

function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(v){return JSON.stringify(v,(k,x)=>typeof x==='number'?Math.round(x*100000)/100000:x,2)}
function num(v,d=1){if(v===null||v===undefined||Number.isNaN(Number(v)))return '—';const n=Number(v);if(Math.abs(n)>=1e9)return(n/1e9).toFixed(d)+'B';if(Math.abs(n)>=1e6)return(n/1e6).toFixed(d)+'M';if(Math.abs(n)>=1e3)return(n/1e3).toFixed(d)+'K';return n.toFixed(d)}
function km(v){if(v===null||v===undefined)return '—';return `${num(v,Number(v)<10?2:1)} KM`}
function iso(v){if(!v)return '—';try{return new Date(v).toISOString().replace('.000Z','Z')}catch{return String(v)}}
function shortIso(v){if(!v)return '—';try{const d=new Date(v);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')} ${String(d.getUTCHours()).padStart(2,'0')}:${String(d.getUTCMinutes()).padStart(2,'0')}:${String(d.getUTCSeconds()).padStart(2,'0')}Z`}catch{return String(v)}}
function distanceAU(pos){return Math.hypot(...(pos||[0,0,0]))/149597870.7}
function svgSpark(values,kind='cyan'){const a=values.length?values:[0,0];const min=Math.min(...a),max=Math.max(...a),span=max-min||1;const pts=a.map((v,i)=>`${i/(a.length-1||1)*100},${31-(v-min)/span*23}`).join(' ');return `<svg class="mini-chart" viewBox="0 0 100 34" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="g-${kind}" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="${kind==='amber'?'#e9bc72':'#9edfff'}" stop-opacity=".25"/><stop offset="1" stop-color="${kind==='amber'?'#e9bc72':'#9edfff'}" stop-opacity="0"/></linearGradient></defs><polyline points="${pts}" fill="none" stroke="${kind==='amber'?'#e9bc72':'#8ed8f8'}" stroke-width="1" vector-effect="non-scaling-stroke"/><polygon points="0,34 ${pts} 100,34" fill="url(#g-${kind})"/></svg>`}
function statusClass(s=''){s=String(s);if(s.includes('VALIDATED')||s==='OK')return'validated';if(s.includes('SCREENING'))return'screening';if(s.includes('PENDING'))return'pending';return'research'}
function statusLabel(s=''){return String(s||'UNAVAILABLE').replaceAll('_',' ')}
function primaryData(x){return x?.data??x}

async function fetchEnvelope(path,options={},updateStatus=false){
  const r=await fetch(path,options);if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);const j=await r.json();
  if(j.request_id)$('#requestId').textContent=j.request_id.slice(0,12).toUpperCase();
  if(updateStatus&&j.data_status){state.primaryDataStatus=j.data_status;$('#dataStatus').textContent=j.data_status}
  return j;
}
async function safeEnvelope(path,options={}){try{return await fetchEnvelope(path,options,false)}catch(e){return{data_status:'UNAVAILABLE',data:null,warnings:[String(e)]}}}

async function loadUniverse(){const env=await fetchEnvelope('/v1/universe',{},false);state.universe=primaryData(env);$('#timeValue').textContent=shortIso(state.universe.current_time_utc);$('#timeModeLabel').textContent=state.universe.time_mode==='NOW'?'UNIVERSAL NOW':state.universe.time_mode.replaceAll('_',' ');$('#focusName').textContent=state.universe.camera_focus||state.universe.selected_object||'EARTH';$('#focusMeta').textContent=state.universe.selected_object?'SELECTED OBJECT':'REFERENCE BODY'}
async function loadGlobalIntel(){const e=await safeEnvelope('/v1/intelligence/important-now');state.globalIntel=Array.isArray(primaryData(e))?primaryData(e):[]}

async function loadMode(mode){
  state.aux={};state.explanation=null;let env;
  if(mode==='SPACE'){
    env=await fetchEnvelope('/v1/space/state',{},true);
    const [events,weather,neo,missions]=await Promise.all(['/v1/space/events','/v1/space-weather/current','/v1/space/neo','/v1/space/missions'].map(p=>safeEnvelope(p)));
    state.aux={events,weather,neo,missions};
  }else if(mode==='CONTROL'){
    env=await fetchEnvelope('/v1/control',{},true);const d=primaryData(env),mission=d?.missions?.[0];
    const upcoming=await safeEnvelope('/v1/launches/upcoming');state.aux.upcoming=upcoming;
    if(mission?.mission_id){const id=encodeURIComponent(mission.mission_id);const [timeline,telemetry,trajectory,handover,objects,windowEnv,stateEnv]=await Promise.all([`/v1/missions/${id}/timeline`,`/v1/missions/${id}/telemetry`,`/v1/missions/${id}/trajectory`,`/v1/missions/${id}/handover`,`/v1/missions/${id}/objects`,`/v1/missions/${id}/window`,`/v1/missions/${id}/state`].map(p=>safeEnvelope(p)));Object.assign(state.aux,{timeline,telemetry,trajectory,handover,objects,window:windowEnv,missionState:stateEnv})}
  }else if(mode==='ORBIT'){
    env=await fetchEnvelope('/v1/orbit',{},true);const [shells,conj,riskGraph,renderSet,reentry]=await Promise.all(['/v1/orbit/shells','/v1/conjunctions','/v1/risk-graph','/v1/orbit/render-set?view=GLOBAL','/v1/reentry'].map(p=>safeEnvelope(p)));state.aux={shells,conj,riskGraph,renderSet,reentry};
  }else if(mode==='INTELLIGENCE'){
    env=await fetchEnvelope('/v1/intelligence/important-now',{},true);const loc=window.AetherusI18n?.locale||'en';const [signals,events,briefing,explanation]=await Promise.all(['/v1/intelligence/signals','/v1/intelligence/events',`/v1/briefings/current?locale=${loc}`,`/v1/llm/explain?locale=${loc}`].map(p=>safeEnvelope(p)));state.aux={signals,events,briefing};state.explanation=primaryData(explanation);
  }else{
    const tm=state.universe.time_mode==='RECONSTRUCTED_STATE'?'RECONSTRUCTED_STATE':state.universe.time_mode==='MODELLED_FUTURE'?'MODELLED_FUTURE':'ARCHIVED_STATE';env=await fetchEnvelope('/v1/archive/time-machine?mode='+encodeURIComponent(tm),{},true);const search=await safeEnvelope('/v1/archive/search');state.aux={search};
  }
  state.envelope=env;state.data=primaryData(env);const sceneMode=(mode==='INTELLIGENCE'||mode==='ARCHIVE')?'CONTROL':mode;state.scene=primaryData(await safeEnvelope('/v1/scene/'+sceneMode));
}

async function selectMode(mode){
  state.mode=mode;state.selectedScale={SPACE:'SOLAR_SYSTEM_VIEW',CONTROL:'EARTH_VIEW',ORBIT:'GLOBAL',INTELLIGENCE:'EVENT_VIEW',ARCHIVE:'ARCHIVED_STATE'}[mode];const preview=currentModeMeta(mode);$('#app').dataset.mode=mode;$$('#modeNav button,#mobileNav button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#modeTitle').textContent=mode;$('#modeIndex').textContent=modeMeta[mode].index;$('#contextTitle').textContent=preview.title;$('#contextSubtitle').textContent=preview.subtitle;$('#captionText').textContent=preview.caption;
  await loadUniverse();await loadMode(mode);if(!state.globalIntel.length)await loadGlobalIntel();render();
}

function render(){
  const m=currentModeMeta(state.mode),d=state.data||{},status=state.primaryDataStatus||state.envelope?.data_status||d.data_status||'UNAVAILABLE';
  $('#contextKicker').textContent=`UNIVERSE / ${state.universe?.time_mode||'NOW'}`;$('#contextTitle').textContent=m.title;$('#contextSubtitle').textContent=m.subtitle;$('#captionText').textContent=m.caption;
  $('#scaleLabel').textContent=state.scene?.scale||state.universe?.space_scale||'—';$('#dataStatus').textContent=status;$('#validationState').textContent=statusLabel(status);$('#validationState').className='validation-badge '+statusClass(status);
  $('#scientificWarning').textContent=d.warning||state.envelope?.warnings?.[0]||scientificWarning(state.mode,status);
  renderLayers();renderViewControls();renderLeft();renderImportant();renderRight();renderBottom();renderStats();renderProvenance();renderInspector();
  visual.setLabels(state.labels);visual.setGrid(state.grid);visual.setMode(state.mode,state.data,state.aux,state.universe,state.scene);$('#focusBack').hidden=!(state.mode==='SPACE'&&visual.focusTarget);applyLocale();
}
function scientificWarning(mode,status){return t(`warning.${mode}`,'Scientific validation boundary applies.')}
function renderLayers(){const layers=state.scene?.layers||[];$('#layerList').innerHTML=layers.length?layers.map(l=>`<div class="layer"><span class="layer-dot"></span><b>${esc(l.layer_id)}</b><small>${esc(l.evidence_class||'')}</small></div>`).join(''):'<div class="empty-state">Layers are context-driven by the selected workspace.</div>'}
function renderViewControls(){let arr=[];if(state.mode==='SPACE')arr=[['SOLAR_SYSTEM_VIEW','SOLAR'],['EARTH_VIEW','EARTH'],['CISLUNAR_VIEW','CISLUNAR']];if(state.mode==='CONTROL')arr=[['EARTH_VIEW','EARTH'],['ORBITAL_VIEW','TARGET ORBIT']];if(state.mode==='ORBIT')arr=[['GLOBAL','GLOBAL'],['LEO','LEO'],['MEO','MEO'],['GEO','GEO'],['EVENT','EVENT']];if(state.mode==='INTELLIGENCE')arr=[['EVENT_VIEW','EVENT'],['EVIDENCE','EVIDENCE']];if(state.mode==='ARCHIVE')arr=[['ARCHIVED_STATE','ARCHIVED'],['RECONSTRUCTED_STATE','RECONSTRUCT']];$('#viewControls').innerHTML=arr.map(([v,l])=>`<button data-view="${v}" class="${v===state.selectedScale?'active':''}">${l}</button>`).join('')}

function renderLeft(){const el=$('#leftDynamic');if(state.mode==='SPACE')el.innerHTML=leftSpace();else if(state.mode==='CONTROL')el.innerHTML=leftControl();else if(state.mode==='ORBIT')el.innerHTML=leftOrbit();else if(state.mode==='INTELLIGENCE')el.innerHTML=leftIntelligence();else el.innerHTML=leftArchive()}
function leftSpace(){const objs=state.data?.objects||[];return `<div class="section-heading"><span>CELESTIAL OBJECTS</span><small>${objs.length} IN LOCAL VIEW</small></div><div class="rail-list">${objs.map(o=>`<div class="rail-item ${o.id==='EARTH'?'active':''}" data-focus="${esc(o.id)}"><div class="row"><b>${esc(o.id)}</b><span class="tag">${distanceAU(o.position_km).toFixed(2)} AU</span></div><small>${esc(o.frame)} · ${esc(o.evidence_class)}</small></div>`).join('')}</div>`}
function leftControl(){const d=state.data||{},missions=d.missions||[];const upcoming=primaryData(state.aux.upcoming)||[];return `<div class="section-heading"><span>MISSION QUEUE</span><small>${upcoming.length?'UPCOMING':'NO VERIFIED LIVE LAUNCH'}</small></div><div class="rail-list">${missions.map(m=>`<div class="rail-item active" data-mission="${esc(m.mission_id)}"><div class="row"><b>${esc(m.name)}</b><span class="tag">${esc(m.status)}</span></div><small>${esc(m.vehicle)} · ${esc(m.sources?.[0]?.source_class||'')}</small></div>`).join('')||'<div class="empty-state">No source-backed mission is available.</div>'}</div><div class="section-heading" style="margin-top:15px"><span>WORKSPACE</span><small>ADAPTIVE</small></div><div class="rail-list">${(d.workspace?.right||[]).slice(0,5).map((x,i)=>`<div class="rail-item ${i===0?'active':''}"><div class="row"><b>${esc(x.replaceAll('_',' '))}</b><span class="tag">${i===0?'PRIMARY':'READY'}</span></div></div>`).join('')}</div>`}
function leftOrbit(){const objs=state.data?.objects||[],shell=state.data?.shell;return `<div class="section-heading"><span>ORBITAL SHELLS</span><small>ENVIRONMENT</small></div><div class="rail-list">${['LEO','MEO','GEO'].map(s=>`<div class="rail-item ${s===shell?.name?'active':''}" data-shell="${s}"><div class="row"><b>${s}</b><span class="tag">${s===shell?.name?`${shell.object_count} OBJECTS`:'CONTEXT'}</span></div><small>${s==='LEO'?'0–2,000 km':s==='MEO'?'2,000–35,786 km':'≈35,786 km'}</small></div>`).join('')}</div><div class="section-heading" style="margin-top:15px"><span>SCREENING OBJECTS</span><small>VALIDATION FIXTURE</small></div><div class="rail-list">${objs.map((o,i)=>`<div class="rail-item ${i===0?'active':''}" data-focus="${esc(o.object_id)}"><div class="row"><b>${esc(o.object_id)}</b><span class="tag">${esc(o.validation_state)}</span></div><small>${esc(o.frame)} · STATE ${esc((o.state_hash||'').slice(0,8))}</small></div>`).join('')}</div>`}
function leftIntelligence(){const packets=Array.isArray(state.data)?state.data:[];return `<div class="section-heading"><span>EVENT QUEUE</span><small>${packets.length} PROMOTED</small></div><div class="rail-list">${packets.map((p,i)=>`<div class="rail-item ${i===0?'active':''}"><div class="row"><b>${esc(p.event?.event_type||'EVENT')}</b><span class="tag">REV ${p.revision?.revision_no??'—'}</span></div><small>${esc(p.event?.mission_id||p.event?.canonical_key||'')}</small></div>`).join('')||'<div class="empty-state">No evidence-backed event is currently promoted.</div>'}</div><div class="section-heading" style="margin-top:15px"><span>INTELLIGENCE GATES</span><small>SCIENTIFIC BOUNDARY</small></div><div class="rail-list"><div class="rail-item"><div class="row"><b>EVIDENCE FUSION</b><span class="tag green">READY</span></div></div><div class="rail-item"><div class="row"><b>SIGNAL PROMOTION</b><span class="tag green">GATED</span></div></div><div class="rail-item"><div class="row"><b>LLM CLAIM VALIDATION</b><span class="tag green">ACTIVE</span></div></div></div>`}
function leftArchive(){const search=primaryData(state.aux.search)||[];return `<div class="section-heading"><span>TIME MACHINE</span><small>${esc(state.universe?.time_mode||'NOW')}</small></div><div class="rail-list"><div class="rail-item ${state.universe?.time_mode!=='RECONSTRUCTED_STATE'?'active':''}" data-timeclass="ARCHIVED_STATE"><div class="row"><b>ARCHIVED STATE</b><span class="tag">IMMUTABLE</span></div><small>Stored historical snapshot</small></div><div class="rail-item ${state.universe?.time_mode==='RECONSTRUCTED_STATE'?'active':''}" data-timeclass="RECONSTRUCTED_STATE"><div class="row"><b>RECONSTRUCTED</b><span class="tag amber">MODELLED</span></div><small>Historical state rebuilt from evidence</small></div></div><div class="section-heading" style="margin-top:15px"><span>ARCHIVE RECORDS</span><small>${search.length}</small></div><div class="rail-list">${search.slice(0,4).map(x=>`<div class="rail-item" data-archive-id="${esc(x.mission_id||x.object_id||x.event_id)}" data-archive-time="${esc(x.time_utc)}"><div class="row"><b>${esc(x.mission_id||x.object_id)}</b><span class="tag">${esc(x.state_kind)}</span></div><small>${shortIso(x.time_utc)}</small></div>`).join('')||'<div class="empty-state">No archive records found.</div>'}</div>`}

function renderImportant(){const packets=state.mode==='INTELLIGENCE'&&Array.isArray(state.data)?state.data:state.globalIntel;const p=packets?.[0];let html='';if(p){const why=(p.why_it_matters||[])[0]||'Evidence-backed event.';html=`<div class="intel-card"><div class="intel-top"><span class="intel-type">${esc(p.event?.event_type||'EVENT')}</span><span class="intel-score">${esc(p.event?.validation_state||'')}</span></div><h4>${esc((p.what_happened||[])[0]||p.event?.canonical_key||'Evidence-backed event')}</h4><p>${esc(why)}</p><div class="intel-foot"><span class="soft-tag">REV ${p.revision?.revision_no??'—'}</span><span class="soft-tag">${p.evidence?.length??0} EVIDENCE</span><span class="soft-tag">APPEND-ONLY</span></div></div>`}else html='<div class="empty-state"><b>Nothing promoted right now.</b><br/>Aetherus stays quiet until evidence clears the promotion gate.</div>';
  if(state.mode==='INTELLIGENCE'&&state.explanation?.text)html+=`<div class="intel-card"><div class="intel-top"><span class="intel-type">AETHERUS EXPLAINS</span><span class="intel-score">PACKET ONLY</span></div><p>${esc(state.explanation.text)}</p><div class="intel-foot"><span class="soft-tag">NO SCIENTIFIC CALCULATION</span></div></div>`;$('#importantNow').innerHTML=html}

function renderRight(){const el=$('#rightDynamic');if(state.mode==='SPACE')el.innerHTML=rightSpace();else if(state.mode==='CONTROL')el.innerHTML=rightControl();else if(state.mode==='ORBIT')el.innerHTML=rightOrbit();else if(state.mode==='INTELLIGENCE')el.innerHTML=rightIntelligence();else el.innerHTML=rightArchive()}
function rightSpace(){const objs=state.data?.objects||[],earth=objs.find(x=>x.id==='EARTH')||objs[0],weather=state.aux.weather||{},neo=state.aux.neo||{};return `<div class="section-heading"><span>SPACE CONTEXT</span><small>CURRENT VIEW</small></div><div class="right-grid"><div class="data-card"><div class="card-head"><span>EARTH / HELIOCENTRIC</span><b>${esc(earth?.frame||'—')}</b></div><div class="primary">${earth?distanceAU(earth.position_km).toFixed(3):'—'} AU</div><div class="secondary">${esc(earth?.provider||'provider unavailable')}</div>${svgSpark(objs.map(o=>distanceAU(o.position_km)))}</div><div class="data-card"><div class="card-head"><span>SPACE WEATHER</span><b>${esc(weather.data_status||'UNAVAILABLE')}</b></div><div class="primary">${weather.data_status==='OK'?'ACTIVE':'—'}</div><div class="secondary">${esc(weather.warnings?.[0]||'NOAA SWPC live feed not verified in local runtime.')}</div></div><div class="data-card"><div class="card-head"><span>NEO WATCH</span><b>${esc(neo.data_status||'UNAVAILABLE')}</b></div><div class="primary">${Array.isArray(neo.data)?neo.data.length:0}</div><div class="secondary">No risk claim is generated without official small-body data.</div></div></div>`}
function rightControl(){const m=state.data?.missions?.[0],timeline=primaryData(state.aux.timeline)||[],telemetry=state.aux.telemetry||{},trajectory=state.aux.trajectory||{},handover=primaryData(state.aux.handover);return `<div class="section-heading"><span>MISSION STREAM</span><small>${esc(m?.status||'NO LIVE MISSION')}</small></div><div class="right-grid"><div class="data-card"><div class="card-head"><span>MISSION</span><b>${esc(m?.mission_id||'—')}</b></div><div class="primary">${esc(m?.name||'UNAVAILABLE')}</div><div class="secondary">${esc(m?.vehicle||'')} · ${esc(m?.sources?.[0]?.source_class||'')}</div></div><div class="data-card"><div class="card-head"><span>TELEMETRY</span><b>${esc(telemetry.data_status||'UNAVAILABLE')}</b></div><div class="primary">${telemetry.data_status==='OK'?'LIVE':'—'}</div><div class="secondary">${esc(telemetry.warnings?.[0]||'No official live telemetry source in local runtime.')}</div></div><div class="data-card"><div class="card-head"><span>MISSION → ORBIT</span><b>${handover?.data_status||state.aux.handover?.data_status||'—'}</b></div><div class="secondary">Payload / stage handover remains evidence-linked to the mission record.</div></div><div class="timeline-list">${timeline.slice(0,4).map(x=>`<div class="timeline-event"><b>${esc(x.event_type||'MISSION EVENT')}</b><small>${shortIso(x.timestamp_utc||x.created_at)}</small></div>`).join('')||`<div class="timeline-event"><b>MISSION RECORD</b><small>${m?.status==='COMPLETE'?'HISTORICAL OFFICIAL FIXTURE':'WAITING FOR EVENT'}</small></div>`}</div></div>`}
function rightOrbit(){const c=state.data?.conjunction||{},risk=state.data?.risk||{},shell=state.data?.shell||{};return `<div class="section-heading"><span>CONJUNCTION WATCH</span><small>${esc(c.validation_state||'')}</small></div><div class="right-grid"><div class="data-card"><div class="card-head"><span>MISS DISTANCE</span><b>${esc(c.method||'')}</b></div><div class="primary red">${km(c.miss_distance_km)}</div><div class="secondary">${esc(c.primary_id)} ↔ ${esc(c.secondary_id)} · TCA ${shortIso(c.tca_utc)}</div>${svgSpark([10,8.7,7.9,7.2,c.miss_distance_km||7,7.4,8.3],'amber')}</div><div class="data-card"><div class="card-head"><span>COLLISION PROBABILITY</span><b>${esc(risk.validation_state||'')}</b></div><div class="primary amber">${risk.pc===null?'UNAVAILABLE':num(risk.pc,6)}</div><div class="secondary">${risk.pc===null?'No covariance → Pc stays null. This is a safety feature, not missing UI.':'Covariance-backed assessment.'}</div></div><div class="data-card"><div class="card-head"><span>${esc(shell.name||'SHELL')} ENVIRONMENT</span><b>${num((shell.coverage_ratio||0)*100,0)}% COVERAGE</b></div><div class="primary">${shell.object_count??0}</div><div class="secondary">Objects in the validation shell · threshold ${esc(shell.threshold_version||'—')}</div></div></div>`}
function rightIntelligence(){const p=(Array.isArray(state.data)?state.data:[])[0]||{};const conf=p.confidence||{},unc=p.uncertainty||{};return `<div class="section-heading"><span>WHY IT MATTERS</span><small>EXPLAINABLE</small></div><div class="right-grid"><div class="data-card"><div class="card-head"><span>WHAT CHANGED</span><b>REV ${p.revision?.revision_no??'—'}</b></div><div class="secondary">${esc((p.what_changed||[])[0]||'No revision delta available.')}</div></div><div class="data-card"><div class="card-head"><span>WHY IT MATTERS</span><b>ATTRIBUTED</b></div><div class="secondary">${esc((p.why_it_matters||[])[0]||'No importance statement available.')}</div></div><div class="data-card"><div class="card-head"><span>CONFIDENCE / UNCERTAINTY</span><b>SEPARATE</b></div><div class="primary">${conf.score!==undefined?num(conf.score*100,0)+'%':'TRACEABLE'}</div><div class="secondary">Confidence never hides uncertainty; both retain evidence lineage.</div></div></div>`}
function rightArchive(){const d=state.data||{},a=d.archive||{},items=a.items||primaryData(state.aux.search)||[];const x=items[0];return `<div class="section-heading"><span>ARCHIVE INTEGRITY</span><small>APPEND-ONLY</small></div><div class="right-grid"><div class="data-card"><div class="card-head"><span>STATE CLASS</span><b>${esc(d.state_class||state.universe?.time_mode||'')}</b></div><div class="primary">${x?esc(x.mission_id||x.state_kind):'—'}</div><div class="secondary">${x?shortIso(x.time_utc):'No archive record at cursor.'}</div></div><div class="data-card"><div class="card-head"><span>CURRENT EVENT MUTATION</span><b class="green">FORBIDDEN</b></div><div class="secondary">Historical replay and reconstruction cannot create a current real-world event.</div></div></div>`}

function renderBottom(){const el=$('#bottomDynamic');if(state.mode==='SPACE'){$('#deckTitle').textContent='SOLAR SYSTEM TELEMETRY';el.innerHTML=bottomSpace()}else if(state.mode==='CONTROL'){$('#deckTitle').textContent='MISSION OPERATIONS';el.innerHTML=bottomControl()}else if(state.mode==='ORBIT'){$('#deckTitle').textContent='ORBITAL RADAR';el.innerHTML=bottomOrbit()}else if(state.mode==='INTELLIGENCE'){$('#deckTitle').textContent='INTELLIGENCE PIPELINE';el.innerHTML=bottomIntelligence()}else{$('#deckTitle').textContent='UNIVERSAL TIMELINE';el.innerHTML=bottomArchive()}$('#deckMeta').textContent=(state.universe?.time_mode||'NOW')+' · '+(state.primaryDataStatus||'')}
function bottomSpace(){const objs=state.data?.objects||[],max=Math.max(0,...objs.map(o=>distanceAU(o.position_km)));return `<div class="deck-cell"><div class="cell-head"><span>TRACKED PLANETS</span><b>LOCAL VIEW</b></div><div class="metric"><strong>${objs.length}</strong><small>OBJECTS</small></div>${svgSpark(objs.map(o=>distanceAU(o.position_km)))}</div><div class="deck-cell"><div class="cell-head"><span>FARTHEST IN VIEW</span><b>NEPTUNE</b></div><div class="metric"><strong>${max.toFixed(1)}</strong><small>AU</small></div><div class="progress-track"><span style="width:92%"></span></div></div><div class="deck-cell"><div class="cell-head"><span>EPHEMERIS</span><b>LOCAL</b></div><div class="micro-list"><div><span>Provider</span><b>KEPLER J2000</b></div><div><span>Frame</span><b>ICRF APPROX</b></div><div><span>Validation</span><b>RESEARCH</b></div></div></div><div class="deck-cell"><div class="cell-head"><span>LIVE PROVIDERS</span><b>GATED</b></div><div class="metric"><strong>0</strong><small>VERIFIED HERE</small></div><div class="secondary warning-line">JPL / SWPC remain staging integrations.</div></div>`}
function bottomControl(){const m=state.data?.missions?.[0],site=m?.launch_site||{},trajectory=state.aux.trajectory||{},trajectoryStatus=trajectory.data_status||'UNAVAILABLE',phase=state.data?.workspace_phase||'PRE-LAUNCH',hasTrajectory=['OK','RESEARCH_ONLY'].includes(trajectoryStatus)&&!!primaryData(trajectory);const trajectoryCell=hasTrajectory?`<div class="deck-cell"><div class="cell-head"><span>TRAJECTORY</span><b>${esc(trajectoryStatus)}</b></div>${svgSpark([.12,.24,.46,.78,.95,.88,.68,.55])}<div class="secondary">Source-backed flight path · ${esc(primaryData(trajectory)?.source_label||'')}</div></div>`:`<div class="deck-cell"><div class="cell-head"><span>TRAJECTORY</span><b class="amber">UNAVAILABLE</b></div><div class="metric"><strong>—</strong></div><div class="secondary warning-line">No source-backed flight path or target orbit is stored.</div></div>`;return `<div class="deck-cell"><div class="cell-head"><span>MISSION PHASE</span><b>${esc(phase.replaceAll('_',' '))}</b></div><div class="metric"><strong>${esc(m?.mission_id||'—')}</strong></div><div class="secondary">${esc(m?.vehicle||'')}</div></div><div class="deck-cell"><div class="cell-head"><span>LAUNCH SITE</span><b>OFFICIAL</b></div><div class="metric"><strong>${site.lat?site.lat.toFixed(2):'—'}°</strong><small>N</small></div><div class="secondary">${site.lon?Math.abs(site.lon).toFixed(2):'—'}° W</div></div>${trajectoryCell}<div class="deck-cell"><div class="cell-head"><span>POST-MISSION RECORD</span><b class="green">${m?.status==='COMPLETE'?'READY':'PENDING'}</b></div><div class="micro-list"><div><span>Mission record</span><b>${m?'READY':'UNAVAILABLE'}</b></div><div><span>Replay</span><b>${m?.status==='COMPLETE'?'READY':'PENDING'}</b></div><div><span>Live telemetry</span><b>UNAVAILABLE</b></div></div></div>`}
function bottomOrbit(){const c=state.data?.conjunction||{},shell=state.data?.shell||{},render=primaryData(state.aux.renderSet)||{};return `<div class="deck-cell"><div class="cell-head"><span>${esc(shell.name||'LEO')} SHELL</span><b>${shell.object_count??0} OBJECTS</b></div><div class="metric"><strong>${num(shell.coverage_ratio*100||0,0)}%</strong><small>COVERAGE</small></div><div class="progress-track"><span style="width:${Math.min(100,(shell.coverage_ratio||0)*100)}%"></span></div></div><div class="deck-cell"><div class="cell-head"><span>CLOSE APPROACH</span><b>SCREENING</b></div><div class="metric"><strong class="red">${num(c.miss_distance_km,2)}</strong><small>KM</small></div>${svgSpark([11,9,8.1,7.4,c.miss_distance_km||7,7.8,9.2],'amber')}</div><div class="deck-cell"><div class="cell-head"><span>SEMANTIC LOD</span><b>VISUAL ONLY</b></div><div class="metric"><strong>${render.render_count??'—'}</strong><small>RENDERED</small></div><div class="secondary">Scientific set: ${render.scientific_count??'—'} · hash unchanged</div></div><div class="deck-cell"><div class="cell-head"><span>Pc</span><b>SAFETY GATE</b></div><div class="metric"><strong class="amber">NULL</strong></div><div class="secondary">Covariance required for probability.</div></div>`}
function bottomIntelligence(){const p=(Array.isArray(state.data)?state.data:[])[0]||{};return ['EVIDENCE','SIGNAL','EVENT','REVISION','WHY IT MATTERS'].map((x,i)=>`<div class="deck-cell"><div class="cell-head"><span>${x}</span><b>${String(i+1).padStart(2,'0')}</b></div><div class="metric"><strong>${i===0?(p.evidence?.length??0):i===1?1:i===2?(p.event?'1':'0'):i===3?(p.revision?.revision_no??0):'→'}</strong><small>${i===0?'SOURCES':i===3?'CURRENT':'GATED'}</small></div><div class="progress-track"><span style="width:${55+i*9}%"></span></div></div>`).join('')}
function bottomArchive(){const s=primaryData(state.aux.search)||[],x=s[0];return `<div class="deck-cell"><div class="cell-head"><span>CURSOR</span><b>${esc(state.universe?.time_mode||'')}</b></div><div class="metric"><strong>${state.universe?new Date(state.universe.current_time_utc).getUTCFullYear():'—'}</strong><small>UTC</small></div></div><div class="deck-cell"><div class="cell-head"><span>ARCHIVE RECORDS</span><b>LOCAL</b></div><div class="metric"><strong>${s.length}</strong><small>INDEXED</small></div></div><div class="deck-cell"><div class="cell-head"><span>EARLIEST RECORD</span><b>OFFICIAL</b></div><div class="metric"><strong>${x?new Date(x.time_utc).getUTCFullYear():'—'}</strong></div><div class="secondary">${esc(x?.mission_id||'')}</div></div><div class="deck-cell"><div class="cell-head"><span>REVISION MODEL</span><b>IMMUTABLE</b></div><div class="micro-list"><div><span>Overwrite history</span><b>NO</b></div><div><span>Replay → current event</span><b>NO</b></div></div></div>`}

function renderStats(){const l=$('#sceneLeftStats'),r=$('#sceneRightStats');if(state.mode==='SPACE'){const objs=state.data?.objects||[];l.innerHTML=`<div class="scene-stat"><strong>${objs.length}</strong><span>PLANETS IN VIEW</span></div><div class="scene-stat"><strong>${state.universe?.time_mode==='NOW'?'NOW':'TIME'}</strong><span>UNIVERSAL STATE</span></div>`;r.innerHTML=`<div class="scene-stat"><span>FRAME</span><strong>ICRF</strong><small>APPROX</small></div><div class="scene-stat"><span>MODEL</span><strong>J2000</strong><small>RESEARCH</small></div>`}else if(state.mode==='CONTROL'){const m=state.data?.missions?.[0];l.innerHTML=`<div class="scene-stat"><strong>${m?.status||'—'}</strong><span>MISSION STATE</span></div>`;r.innerHTML=`<div class="scene-stat"><span>VEHICLE</span><strong>${esc(m?.vehicle?.split(' ')[0]||'—')}</strong></div><div class="scene-stat"><span>TELEMETRY</span><strong>—</strong><small>UNAVAILABLE</small></div>`}else if(state.mode==='ORBIT'){const c=state.data?.conjunction||{};l.innerHTML=`<div class="scene-stat"><strong>${num(c.miss_distance_km,2)}</strong><span>KM MISS DISTANCE</span></div>`;r.innerHTML=`<div class="scene-stat"><span>Pc</span><strong>NULL</strong><small>NO COVARIANCE</small></div><div class="scene-stat"><span>TCA</span><strong>${c.tca_utc?new Date(c.tca_utc).toISOString().slice(11,19):'—'}</strong><small>UTC</small></div>`}else if(state.mode==='INTELLIGENCE'){const p=(Array.isArray(state.data)?state.data:[])[0]||{};l.innerHTML=`<div class="scene-stat"><strong>${p.evidence?.length??0}</strong><span>EVIDENCE SOURCES</span></div>`;r.innerHTML=`<div class="scene-stat"><span>REVISION</span><strong>${p.revision?.revision_no??0}</strong><small>APPEND-ONLY</small></div>`}else{const s=primaryData(state.aux.search)||[];l.innerHTML=`<div class="scene-stat"><strong>${s.length}</strong><span>ARCHIVE RECORDS</span></div>`;r.innerHTML=`<div class="scene-stat"><span>STATE</span><strong>${(state.data?.state_class||'ARCHIVED').replace('_STATE','')}</strong></div>`}}
function renderProvenance(){let html='';if(state.mode==='SPACE'){const o=state.data?.objects?.[0];html=`<b>${esc(o?.provider||'AETHERUS LOCAL')}</b><br/>${esc(o?.kernel_version||'mean-elements-j2000-v1')}<br/><span class="warning-line">RESEARCH_ONLY — not a JPL precision substitute.</span>`}else if(state.mode==='CONTROL')html='<b>NASA fixed official historical fixture</b><br/>Mission record provenance is preserved. Modelled trajectory is displayed separately from telemetry.';else if(state.mode==='ORBIT')html='<b>VALIDATION_FIXTURE / SCREENING_ONLY</b><br/>TEME_APPROX orbit state. Covariance unavailable, so collision probability remains null.';else if(state.mode==='INTELLIGENCE')html='<b>Evidence → Signal → Event → Revision</b><br/>Important claims retain source, evidence, confidence and uncertainty lineage.';else html='<b>Append-only archive</b><br/>Stored historical snapshots are visually distinct from reconstructed or modelled states.';$('#provenance').innerHTML=html}
function renderInspector(){const payload={data_status:state.primaryDataStatus,universe:state.universe,scene:state.scene,data:state.data,warnings:state.envelope?.warnings||[]};$('#detailPanel').textContent=fmt(payload)}

function phaseAuthHeaders(){let token='';try{token=sessionStorage.getItem('aetherus.stagingToken')||''}catch{}const headers={'Content-Type':'application/json','X-Aetherus-Tenant':'DEVICE-TEST','X-Aetherus-User':'PHASE-VALIDATOR','X-Aetherus-Plan':'OPERATIONS'};if(token)headers.Authorization=`Bearer ${token}`;return headers}
async function patchUniverse(body,soft=false){const headers=phaseAuthHeaders();if(soft&&!headers.Authorization)return false;try{await fetchEnvelope('/v1/universe',{method:'PATCH',headers,body:JSON.stringify(body)},false);return true}catch(error){if(soft&&(String(error).startsWith('401')||String(error).startsWith('503')))return false;throw error}}
async function focusSpaceObject(id){visual.setFocus(id);state.selectedScale='PLANET_FOCUS';$('#focusName').textContent=id;$('#focusMeta').textContent='PLANET FOCUS';$('#focusBack').hidden=false;$('#scaleLabel').textContent='PLANET_FOCUS';await patchUniverse({selected_object:id,camera_focus:id,space_scale:'PLANET_FOCUS'},true)}
async function clearSpaceFocus(){visual.clearFocus();state.selectedScale='SOLAR_SYSTEM_VIEW';$('#focusName').textContent='EARTH';$('#focusMeta').textContent='REFERENCE BODY';$('#focusBack').hidden=true;$('#scaleLabel').textContent='SOLAR_SYSTEM_VIEW';await patchUniverse({camera_focus:'EARTH',space_scale:'SOLAR_SYSTEM_VIEW'},true)}
async function focusArchiveRecord(id,timeUtc){if(!id||!timeUtc)return;visual.setArchiveSelection(id,timeUtc);if(state.universe){state.universe.current_time_utc=timeUtc;state.universe.time_mode='ARCHIVED_STATE'}$('#focusName').textContent=id;$('#focusMeta').textContent='ARCHIVED RECORD';$('#timeValue').textContent=shortIso(timeUtc);$('#timeModeLabel').textContent='ARCHIVED STATE';await patchUniverse({current_time_utc:timeUtc,time_mode:'ARCHIVED_STATE',camera_focus:id},true)}
function phaseRequest(path,body){return fetchEnvelope(path,{method:'POST',headers:phaseAuthHeaders(),body:JSON.stringify(body)},false)}
function phaseSummary(phase,data){if(phase==='P6')return `${phase} · ${data.candidates?.length||0} candidates · ${(data.result_hash||'').slice(0,12)}`;if(phase==='P7')return `${phase} · ${data.child_id||'DEBRIS'} · ${data.evidence_id||'EVIDENCE'}`;if(phase==='P8')return `${phase} · ${data.fragments?.length||0} fragments · ${(data.result_hash||'').slice(0,12)}`;if(phase==='P9')return `${phase} · ${data.windows?.length||0} visibility windows · ${(data.result_hash||'').slice(0,12)}`;if(phase==='P10')return `${phase} · ${data.manifest?.record_count||0} records · ${(data.manifest?.dataset_hash||'').slice(0,12)}`;if(phase==='P11')return `${phase} · ${data.status||'EXECUTED'} · ${(data.job_id||'').slice(0,12)}`;return `${phase} · ${data.local_product_complete?'LOCAL COMPLETE':'HARDENING ACTIVE'} · ${(data.blockers||[]).length} external gates`}
async function runPhase(phase){const result=$('#phaseResult'),button=$(`[data-phase-run="${phase}"]`);result.dataset.phase=phase;result.dataset.state='RUNNING';result.innerHTML=`<b>${phase} · RUNNING</b><span>INPUT → COMPUTE → PERSISTENCE → API</span>`;button?.classList.add('running');try{let env;if(phase==='P6')env=await phaseRequest('/v1/protect/PROTECTED/candidates',{protected_active:true,primary_state:{object_id:'PROTECTED',position_km:[7000,0,0],velocity_km_s:[0,7.5,0]},encounter_states:[{object_id:'THREAT-AHEAD',position_km:[7000,20,0],velocity_km_s:[0,7.46,0]},{object_id:'OBJECT-BEHIND',position_km:[7000,-20,0],velocity_km_s:[0,7.5,0]}],candidates:[{candidate_id:'RADIAL-SAFE',delta_v_m_s:[20,0,0]},{candidate_id:'RETROGRADE-TRADEOFF',delta_v_m_s:[0,-40,0]}],horizon_s:600,step_s:10,risk_threshold_km:5});else if(phase==='P7')env=await phaseRequest('/v1/genealogy/DEBRIS-DEVICE-TEST',{parent_id:'VAL-A',origin:'VALIDATION_FRAGMENTATION',event_time_utc:'2026-08-31T00:00:00Z',evidence_id:'DEVICE-VALIDATION-EVIDENCE',known:true});else if(phase==='P8')env=await phaseRequest('/v1/scenarios/fragmentation',{kind:'FRAGMENTATION',target_object_ids:['VAL-A'],parameters:{delta_v_scale_m_s:12},assumptions:['DEVICE_VALIDATION_FIXTURE'],seed:23,fragment_count:12,parent_state:{object_id:'VAL-A',position_km:[7000,0,0],velocity_km_s:[0,7.5,0]},encounter_states:[],horizon_s:900,step_s:30,affected_distance_km:5});else if(phase==='P9')env=await phaseRequest('/v1/observations/requests',{station:{station_id:'EQUATOR-0',latitude_deg:0,longitude_deg:0,altitude_m:0},object_state:{object_id:'VAL-A',position_km:[1270.917571,-6883.669589,0],velocity_km_s:[7.37536,1.361697,0]},start_utc:'2000-01-01T12:00:00Z',end_utc:'2000-01-01T12:20:00Z',step_s:10,minimum_elevation_deg:10,mount_rate_limit_deg_s:5});else if(phase==='P10')env=await phaseRequest('/v1/research/datasets',{dataset_key:'DEVICE-OBSERVATION-PLANS',version:'2026-08-31',domain:'ORBIT',record_type:'OBSERVATION_PLAN',license_policy:'CC-BY-4.0'});else if(phase==='P11')env=await phaseRequest('/v1/operations/jobs',{operation:'ECHO',payload:{source:'P11_DEVICE_VALIDATION'},idempotency_key:'p11-device-validation',run_now:true,max_attempts:3});else env=await fetchEnvelope('/v1/platform/readiness',{headers:phaseAuthHeaders()},false);const data=primaryData(env)||{};result.dataset.state='PASS';result.innerHTML=`<b>${esc(phase)} · EXECUTED</b><span>${esc(phaseSummary(phase,data))}</span>`}catch(error){result.dataset.state='FAIL';result.innerHTML=`<b>${esc(phase)} · FAILED</b><span>${esc(String(error))}</span>`}finally{button?.classList.remove('running')}}
async function shiftTime(ms){const t=new Date(state.universe.current_time_utc);t.setTime(t.getTime()+ms);await patchUniverse({current_time_utc:t.toISOString(),time_mode:ms<0?'RECONSTRUCTED_STATE':'MODELLED_FUTURE'});await selectMode(state.mode)}
async function setTimeClass(mode){await patchUniverse({time_mode:mode});await selectMode('ARCHIVE')}

$('#modeNav').addEventListener('click',e=>{const b=e.target.closest('button[data-mode]');if(b)selectMode(b.dataset.mode)});
$('#resetNow').addEventListener('click',async()=>{await patchUniverse({current_time_utc:new Date().toISOString(),time_mode:'NOW'});await selectMode(state.mode)});
$('#pastBtn').addEventListener('click',()=>shiftTime(-86400000));$('#futureBtn').addEventListener('click',()=>shiftTime(86400000));
$('#toggleLabels').addEventListener('click',e=>{state.labels=!state.labels;e.currentTarget.dataset.active=String(state.labels);visual.setLabels(state.labels)});$('#toggleGrid').addEventListener('click',e=>{state.grid=!state.grid;e.currentTarget.dataset.active=String(state.grid);visual.setGrid(state.grid)});
$('#viewControls').addEventListener('click',async e=>{const b=e.target.closest('button[data-view]');if(!b)return;$$('#viewControls button').forEach(x=>x.classList.toggle('active',x===b));const v=b.dataset.view;state.selectedScale=v;if(state.mode==='SPACE'&&v==='SOLAR_SYSTEM_VIEW'){await clearSpaceFocus()}else if(state.mode==='ORBIT'){visual.setOrbitView(v);$('#scaleLabel').textContent=v;if(['LEO','MEO','GEO'].includes(v)){await patchUniverse({active_orbital_shell:v,space_scale:'ORBITAL_VIEW',camera_focus:v},true);await loadUniverse();render()}}else if(state.mode==='ARCHIVE'&&v.includes('STATE'))await setTimeClass(v);else if(['EARTH_VIEW','CISLUNAR_VIEW','ORBITAL_VIEW','EVENT_VIEW'].includes(v)){await patchUniverse({space_scale:v},true);await loadUniverse();$('#scaleLabel').textContent=v}});
$('.left-rail').addEventListener('click',async e=>{const f=e.target.closest('[data-focus]');if(f){if(state.mode==='SPACE')await focusSpaceObject(f.dataset.focus);else{await patchUniverse({camera_focus:f.dataset.focus,selected_object:f.dataset.focus});await loadUniverse();render()}}const s=e.target.closest('[data-shell]');if(s){await patchUniverse({active_orbital_shell:s.dataset.shell,camera_focus:s.dataset.shell,space_scale:'ORBITAL_VIEW'});await loadUniverse();render()}const m=e.target.closest('[data-mission]');if(m){await patchUniverse({active_mission:m.dataset.mission,camera_focus:'EARTH'});await loadUniverse();await loadMode('CONTROL');render()}const ar=e.target.closest('[data-archive-id]');if(ar)await focusArchiveRecord(ar.dataset.archiveId,ar.dataset.archiveTime);const tc=e.target.closest('[data-timeclass]');if(tc)await setTimeClass(tc.dataset.timeclass)});
$('#focusBack').addEventListener('click',clearSpaceFocus);


$('#mobileNav').addEventListener('click',e=>{const b=e.target.closest('button[data-mode]');if(b){selectMode(b.dataset.mode);$('#mobileSheet').classList.remove('open');$('#mobileSheetHandle').setAttribute('aria-expanded','false')}});
$('#localeToggle').addEventListener('click',async()=>{const next=window.AetherusI18n?.locale==='ko'?'en':'ko';window.AetherusI18n?.setLocale(next);if(state.mode==='INTELLIGENCE')await loadMode('INTELLIGENCE');render()});
$('#mobileSheetHandle').addEventListener('click',()=>{const el=$('#mobileSheet');const open=el.classList.toggle('open');$('#mobileSheetHandle').setAttribute('aria-expanded',String(open))});
$('#phaseWorkspace').addEventListener('click',e=>{const button=e.target.closest('[data-phase-run]');if(button)runPhase(button.dataset.phaseRun)});$('#saveStagingToken').addEventListener('click',()=>{try{sessionStorage.setItem('aetherus.stagingToken',$('#stagingToken').value.trim())}catch{}$('#phaseResult').dataset.state='IDLE';$('#phaseResult').innerHTML=`<b>TOKEN · SESSION ONLY</b><span>Stored only in this browser tab session.</span>`});try{$('#stagingToken').value=sessionStorage.getItem('aetherus.stagingToken')||''}catch{}
let sheetStartY=null;$('#mobileSheet').addEventListener('touchstart',e=>{sheetStartY=e.touches?.[0]?.clientY??null},{passive:true});$('#mobileSheet').addEventListener('touchend',e=>{if(sheetStartY===null)return;const y=e.changedTouches?.[0]?.clientY??sheetStartY;const dy=y-sheetStartY;if(Math.abs(dy)>36){const open=dy<0;$('#mobileSheet').classList.toggle('open',open);$('#mobileSheetHandle').setAttribute('aria-expanded',String(open))}sheetStartY=null},{passive:true});

visual=new AetherusVisualEngine($('#spaceGlCanvas'),$('#universeCanvas'));visual.onSelect=async h=>{if(h.type==='OBJECT'){if(state.mode==='SPACE')await focusSpaceObject(h.id);else{await patchUniverse({selected_object:h.id,camera_focus:h.id},true);$('#focusName').textContent=h.id;$('#focusMeta').textContent='SELECTED OBJECT'}}else if(h.type==='ARCHIVE_RECORD')await focusArchiveRecord(h.id,h.data?.time_utc)};window.__AETHERUS_VISUAL__=Object.freeze({snapshot:()=>visual.snapshot()});visual.start();
Promise.all([loadGlobalIntel(),selectMode('SPACE')]).catch(e=>{$('#runtimeStatus').textContent='RUNTIME ERROR';$('#runtimeSubstatus').textContent=String(e).slice(0,60);$('#detailPanel').textContent=String(e);console.error(e)});

// App-shell offline support only. Scientific/API responses are deliberately never cached by the service worker.
if('serviceWorker' in navigator && (location.protocol==='https:' || location.hostname==='localhost' || location.hostname==='127.0.0.1')){
  navigator.serviceWorker.register('/app/sw.js',{scope:'/app/'}).catch(()=>{});
}
