import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {PNG} from 'pngjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),prototypeRoot=path.join(root,'prototype'),out=path.resolve(process.env.EARTHUS_V2_TRENCH_OUTPUT||path.join(root,'output/v2-trench-mesh-visual')),moduleRef=process.env.EARTHUS_PLAYWRIGHT_MODULE;
const {chromium}=moduleRef?await import(pathToFileURL(path.resolve(moduleRef)).href):await import('playwright');
const CLOUD='https://earthus-cache-kr.s3.us-east-2.amazonaws.com',MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'};
function server(){return http.createServer(async(req,res)=>{let p;try{p=decodeURIComponent(new URL(req.url,'http://x').pathname)}catch{res.writeHead(400).end();return}if(p.startsWith('/clouds/')){try{const r=await fetch(CLOUD+p,{cache:'no-store'}),b=Buffer.from(await r.arrayBuffer());res.writeHead(r.status,{'Content-Type':r.headers.get('content-type')||'application/octet-stream','Access-Control-Allow-Origin':'*','Cache-Control':'no-store'}).end(b)}catch(e){res.writeHead(502).end(String(e))}return}if(p==='/'||p==='/v2'||p==='/v2/')p='/v2/index.html';const f=path.resolve(prototypeRoot,'.'+p);if(!f.startsWith(prototypeRoot+path.sep)){res.writeHead(403).end();return}fs.readFile(f,(e,b)=>e?res.writeHead(404).end():res.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'}).end(b))})}
async function wait(page,fn,ms=90000){const end=Date.now()+ms;while(Date.now()<end){try{if(await page.evaluate(fn))return}catch{}await page.waitForTimeout(200)}throw new Error('TRENCH_FOCUSED_WAIT_TIMEOUT')}
async function pixels(page){const b64=await page.evaluate(()=>{const v=window.__earthusV2?.viewer,s=v?.scene;if(!s)throw new Error('SCENE_MISSING');s.requestRender();s.render();const gl=s.context?._gl,w=gl?.drawingBufferWidth,h=gl?.drawingBufferHeight;if(!(w>0&&h>0))throw new Error('GL_MISSING');const raw=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,raw);const flipped=new Uint8ClampedArray(raw.length),row=w*4;for(let y=0;y<h;y++)flipped.set(raw.subarray((h-1-y)*row,(h-y)*row),y*row);const cv=document.createElement('canvas');cv.width=w;cv.height=h;cv.getContext('2d').putImageData(new ImageData(flipped,w,h),0,0);return cv.toDataURL('image/png').split(',')[1]});return Buffer.from(b64,'base64')}
function metrics(buf){const p=PNG.sync.read(buf),d=p.data;let n=0,sum=0,sum2=0,dark=0;const vals=[];for(let y=Math.floor(p.height*.08);y<p.height*.92;y+=2)for(let x=Math.floor(p.width*.08);x<p.width*.92;x+=2){const i=(y*p.width+x)*4,l=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/255;n++;sum+=l;sum2+=l*l;vals.push(l);if(l<.02)dark++}vals.sort((a,b)=>a-b);const mean=sum/n,std=Math.sqrt(Math.max(0,sum2/n-mean*mean)),p10=vals[Math.floor(vals.length*.1)]||0,p90=vals[Math.floor(vals.length*.9)]||0;return{mean,std,range:p90-p10,darkRatio:dark/n}}
fs.mkdirSync(out,{recursive:true});const srv=server();await new Promise(r=>srv.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});const page=await browser.newPage({viewport:{width:1280,height:800}});page.setDefaultTimeout(100000);const state={};
try{console.log('TRENCH FOCUSED boot');await page.goto(`http://127.0.0.1:${srv.address().port}/v2/`,{waitUntil:'domcontentloaded',timeout:60000});await wait(page,()=>document.documentElement.dataset.c==='1'&&!!window.__earthusV2?.realEarth,60000);console.log('TRENCH FOCUSED enter');state.entered=await page.evaluate(()=>window.__earthusV2.realEarth.enterTrench());assert.equal(state.entered,true);await wait(page,()=>window.__earthusV2.realEarth.trenchMeshTruth?.()?.truthClass==='ESRI_TOPOBATHY3D_SAMPLED_SEAFLOOR_MESH',90000);state.runtime=await page.evaluate(()=>({mesh:window.__earthusV2.realEarth.trenchMeshTruth(),sample:window.__earthusV2.realEarth.trenchSample(),terrain:window.__earthusV2.realEarth.terrainTruth(),cameraHeight:window.__earthusV2.viewer.camera.positionCartographic.height,pitch:Cesium.Math.toDegrees(window.__earthusV2.viewer.camera.pitch),translucency:window.__earthusV2.viewer.scene.globe.translucency.enabled,front:window.__earthusV2.viewer.scene.globe.translucency.frontFaceAlpha,badge:document.getElementById('earthusV2RealSources')?.textContent||null}));assert.equal(state.runtime.terrain,'ESRI_TOPOBATHY3D');assert.equal(state.runtime.mesh?.truthClass,'ESRI_TOPOBATHY3D_SAMPLED_SEAFLOOR_MESH');assert.equal(state.runtime.mesh?.synthetic,false);assert.equal(state.runtime.mesh?.verticalExaggeration,1);assert.ok(state.runtime.mesh?.deepestM>8000);assert.ok(state.runtime.mesh?.triangleCount>600);assert.ok(state.runtime.sample?.depthM>8000);assert.equal(state.runtime.translucency,true);const buf=await pixels(page);fs.writeFileSync(path.join(out,'trench.png'),buf);state.metrics=metrics(buf);assert.ok(state.metrics.mean>.012,`mean:${state.metrics.mean}`);assert.ok(state.metrics.std>.012,`std:${state.metrics.std}`);assert.ok(state.metrics.range>.035,`range:${state.metrics.range}`);assert.ok(state.metrics.darkRatio<.88,`dark:${state.metrics.darkRatio}`);fs.writeFileSync(path.join(out,'state.json'),JSON.stringify({ok:true,...state},null,2));console.log('V2 TRENCH SAMPLED MESH VISUAL: PASS',JSON.stringify(state));}catch(error){fs.writeFileSync(path.join(out,'state.json'),JSON.stringify({ok:false,error:String(error?.stack||error),...state},null,2));throw error}finally{await browser.close();await new Promise(r=>srv.close(r))}
