#!/usr/bin/env node
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const directory = await mkdtemp(path.join(os.tmpdir(), 'aetherus-citizen-science-'));
const source = await readFile(path.join(ROOT, 'prototype/js/space/citizen-science.js'), 'utf8');
await writeFile(path.join(directory, 'citizen-science.mjs'), source);
const science = await import(pathToFileURL(path.join(directory, 'citizen-science.mjs')).href);
let tick = 0; const now = () => new Date(Date.UTC(2026, 7, 12, 11, 0, tick++)); let ids = 0; const idFactory = prefix => `${prefix}_fixture_${++ids}`;
const repository = science.createMemoryCitizenScienceRepository();
const service = science.createCitizenScienceService({ repository, now, idFactory });
const campaign = await service.createCampaign({ idempotencyKey: 'campaign', input: { id: 'meteor-campaign-fixture', ownerId: 'operator-a', state: 'DRAFT', requirements: { allowedObservationTypes: ['METEOR'], requiresWcs: true, requiresLicense: true, locationPolicy: 'COARSE_REGION' } } });
assert.equal(campaign.result.state, 'DRAFT');
const opened = await service.openCampaign({ campaignId: campaign.result.id, ownerId: 'operator-a', idempotencyKey: 'open' });
assert.equal(opened.result.state, 'OPEN');
const input = { ownerId: 'principal-a', observationId: 'obs-meteor-1', observationType: 'METEOR', observedAtUtc: '2026-08-12T10:30:00.000Z', consent: true, provenance: { classification: 'observation', sourceRevision: 'session-r1', precision: 'WCS_VERIFIED' }, wcs: { status: 'VERIFIED', solutionDigest: 'b'.repeat(64) }, rights: { share: 'ALLOWED', license: 'CC BY 4.0', credit: 'observer' }, location: { coarseRegion: 'seoul-metropolitan-area' }, evidenceDigest: 'c'.repeat(64) };
const submitted = await service.submit({ campaignId: campaign.result.id, input, idempotencyKey: 'submit' });
assert.equal(submitted.result.state, 'PENDING_REVIEW');
const duplicate = await service.submit({ campaignId: campaign.result.id, input, idempotencyKey: 'submit-duplicate' });
assert.equal(duplicate.result.duplicateOf, submitted.result.id);
await assert.rejects(() => service.submit({ campaignId: campaign.result.id, idempotencyKey: 'missing-consent', input: { ...input, observationId: 'obs-meteor-2', consent: false } }), error => error.code === 'SCIENCE_CONSENT_REQUIRED');
await assert.rejects(() => service.submit({ campaignId: campaign.result.id, idempotencyKey: 'invalid-wcs', input: { ...input, observationId: 'obs-meteor-3', wcs: { status: 'UNVERIFIED' } } }), error => error.code === 'SCIENCE_WCS_VERIFICATION_REQUIRED');
await assert.rejects(() => service.partnerPackage({ submissionId: submitted.result.id, partnerId: 'partner-a' }), error => error.code === 'SCIENCE_PARTNER_EXPORT_REVIEW_REQUIRED');
const accepted = await service.review({ submissionId: submitted.result.id, reviewerId: 'reviewer-a', decision: 'ACCEPTED', reason: 'campaign requirements verified', idempotencyKey: 'accept' });
assert.equal(accepted.result.state, 'ACCEPTED');
const partner = await service.partnerPackage({ submissionId: submitted.result.id, partnerId: 'partner-a' });
assert.equal(partner.location.policy, 'COARSE_REGION');
assert.equal(partner.exclusions.includes('EXACT_LOCATION'), true);
assert.equal('ownerId' in partner, false);
const retracted = await service.retract({ submissionId: submitted.result.id, ownerId: 'principal-a', explicitUserConfirmation: true, idempotencyKey: 'retract' });
assert.equal(retracted.result.state, 'RETRACTED');
assert.doesNotMatch(source, /\bfetch\s*\(/, 'no partner upload or campaign API');
assert.match(source, /reviewerId: token\(reviewerId/, 'only a named human reviewer may create an ACCEPTED decision');
console.log('PASS: campaign requirements, consent/WCS/rights gates, duplicate rejection, human review, retraction, and minimized partner package');
