import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { PNG } from 'pngjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const prototypeRoot=path.join(root,'prototype');
const outputRoot=path.resolve(process.env.EARTHUS_V2_VISUAL_OUTPUT||path.join(root,'output/v2-real-living-earth-visual'));
const moduleRef=process.env.EARTHUS_PLAYWRIGHT_MODULE;
const playwright=moduleRef?await import(pathToFileURL(path.resolve(moduleRef)).href):await import('playwright');
const {chromium}=playwright;
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.jpg':'image/jpeg','.jpeg':'image/jpeg'};
const CLOUD_ORIGIN='https://earthus-cache-kr.s3.us-east-2.amazonaws.com';

function localServer(){return http.createServer(async(req,res)=>{let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname)}catch(_){res.writeHead(400).end('bad request');return}if(pathname.startsWith('/clouds/')){try{const remote=await fetch(`${CLOUD_ORIGIN}${pathname}`,{cache:'no-store'});const body=Buffer.from(await remote.arrayBuffer());res.writeHead(remote.status,{'Content-Type':remote.headers.get('content-type')||'application/octet-stream','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(body)}catch(error){res.writeHead(502).end(String(error?.message||error))}return}if(pathname==='/')pathname='/index.html';if(pathname==='/v2'||pathname==='/v2/')pathname='/v2/index.html';const target=path.resolve(prototypeRoot,`.${pathname}`);if(!target.startsWith(`${prototypeRoot}${path.sep}`)){res.writeHead(403).end('forbidden');return}fs.readFile(target,(error,body)=>{if(error){res.writeHead(error.code==='ENOENT'?404:500).end('not found');return}res.writeHead(200,{'Content-Type':MIME[path.extname(target)]||'application/octet-stream','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(body)})})}
async function waitFor(page,fn,timeout=45000){const end=Date.now()+timeout;while(Date.now()<end){try{if(await page.evaluate(fn))return true}catch(_){}await page.waitForTimeout(250)}throw new Error('V2_VISUAL_WAIT_TIMEOUT')}
async function settleGlobe(page,{minimumMs=3500,maximumMs=15000}={}){const started=Date.now();let loadedStreak=0;while(Date.now()-started<maximumMs){await page.evaluate(()=>window.__earthusV2?.viewer?.scene?.requestRender?.());await page.waitForTimeout(350);const loaded=await page.evaluate(()=>window.__earthusV2?.viewer?.scene?.globe?.tilesLoaded===true);if(Date.now()-started>=minimumMs){loadedStreak=loaded?loadedStreak+1:0;if(loadedStreak>=3)return true}}return false}
function pngSignal(buffer,region={x0:.18,x1:.94,y0:.08,y1:.88}){const png=PNG.sync.read(buffer),{width,height,data}=png,x0=Math.floor(width*region.x0),x1=Math.floor(width*region.x1),y0=Math.floor(height*region.y0),y1=Math.floor(height*region.y1),values=[];let sum=0,sum2=0,n=0,dark=0,bright=0;for(let y=y0;y<y1;y+=2)for(let x=x0;x<x1;x+=2){const i=(y*width+x)*4;if(data[i+3]<8)continue;const l=(.2126*data[i]+.7152*data[i+1]+.0722*data[i+2])/255;values.push(l);sum+=l;sum2+=l*l;n++;if(l<.02)dark++;if(l>.1)bright++}if(!n)throw new Error('V2_VISUAL_PNG_EMPTY');values.sort((a,b)=>a-b);const mean=sum/n,std=Math.sqrt(Math.max(0,sum2/n-mean*mean)),p10=values[Math.floor(values.length*.1)]??0,p90=values[Math.floor(values.length*.9)]??0;return Object.freeze({width,height,samples:n,mean:Number(mean.toFixed(5)),std:Number(std.toFixed(5)),p10:Number(p10.toFixed(5)),p90:Number(p90.toFixed(5)),dynamicRange:Number((p90-p10).toFixed(5)),darkRatio:Number((dark/n).toFixed(5)),brightRatio:Number((bright/n).toFixed(5))})}
function assertSignal(name,m,{minStd,minRange,minMean=0,maxDarkRatio=1}={}){assert.ok(m.mean>=minMean,`${name} frame is too dark: mean=${m.mean}`);assert.ok(m.std>=minStd,`${name} frame lacks visual structure: std=${m.std}`);assert.ok(m.dynamicRange>=minRange,`${name} frame lacks terrain/texture contrast: range=${m.dynamicRange}`);assert.ok(m.darkRatio<=maxDarkRatio,`${name} frame has an excessive black region: darkRatio=${m.darkRatio}`)}
async function pageState(page){return page.evaluate(()=>{const rt=window.__earthusV2,viewer=rt?.viewer,scene=viewer?.scene,canvas=document.querySelector('.cesium-widget canvas'),fallback=document.querySelector('.fallback');let renderer=null,max3d=null;try{const gl=scene?.context?._gl||canvas?.getContext('webgl2'),ext=gl?.getExtension('WEBGL_debug_renderer_info');renderer=ext?String(gl.getParameter(ext.UNMASKED_RENDERER_WEBGL)||''):String(gl?.getParameter(gl.RENDERER)||'');max3d=gl?Number(gl.getParameter(gl.MAX_3D_TEXTURE_SIZE)||0):null}catch(_){}const layers=[];if(viewer?.imageryLayers)for(let i=0;i<viewer.imageryLayers.length;i++){const l=viewer.imageryLayers.get(i),p=l.imageryProvider;layers.push({index:i,show:l.show,alpha:l.alpha,provider:p?.constructor?.name||null,ready:p?.ready??null,url:p?.url||p?._resource?.url||null})}const cart=viewer?.camera?.positionCartographic;return{sourceBadge:document.getElementById('earthusV2RealSources')?.textContent||null,dataC:document.documentElement.dataset.c||null,fallbackDisplay:fallback?getComputedStyle(fallback).display:null,terrainTruth:rt?.realEarth?.terrainTruth?.()||null,bathymetryTruth:rt?.realEarth?.bathymetryTruth?.()||null,polarTruth:rt?.realEarth?.polarTruth?.()||null,polarSources:rt?.realEarth?.polarSources?.()||[],cloudFidelity:rt?.realEarth?.cloudFidelity?.()||null,cloudDiagnostics:rt?.realEarth?.cloudDiagnostics?.()||null,waterTruth:rt?.realEarth?.waterTruth?.()||null,trenchSample:rt?.realEarth?.trenchSample?.()||null,cameraHeight:cart?.height??null,cameraLatitudeDeg:cart?Cesium.Math.toDegrees(cart.latitude):null,cameraLongitudeDeg:cart?Cesium.Math.toDegrees(cart.longitude):null,cameraPitchDeg:viewer?.camera?Cesium.Math.toDegrees(viewer.camera.pitch):null,imageryLayers:viewer?.imageryLayers?.length??null,imageryLayerDetails:layers,primitives:scene?.primitives?.length??null,globeTilesLoaded:scene?.globe?.tilesLoaded??null,globeLighting:scene?.globe?.enableLighting??null,groundAtmosphere:scene?.globe?.showGroundAtmosphere??null,skyAtmosphere:scene?.skyAtmosphere?.show??null,sun:scene?.sun?.show??null,skyPanoramaVisible:globalThis.__earthusSkyPanorama?.visible??null,translucencyEnabled:scene?.globe?.translucency?.enabled??null,frontFaceAlpha:scene?.globe?.translucency?.frontFaceAlpha??null,backFaceAlpha:scene?.globe?.translucency?.backFaceAlpha??null,canvas:canvas?{cssWidth:canvas.clientWidth,cssHeight:canvas.clientHeight,width:canvas.width,height:canvas.height}:null,webgl2:!!canvas?.getContext('webgl2'),renderer,max3d}})}
const visualMetrics={};
async function snapshot(page,cdp,name){await page.evaluate(()=>window.__earthusV2?.viewer?.scene?.requestRender?.());await page.waitForTimeout(350);const {data}=await cdp.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false}),buffer=Buffer.from(data,'base64');fs.writeFileSync(path.join(outputRoot,`${name}.png`),buffer);visualMetrics[name]=pngSignal(buffer);if(name==='01b-polar')visualMetrics[`${name}-center`]=pngSignal(buffer,{x0:.35,x1:.65,y0:.25,y1:.75});return pageState(page)}
async function setPolarView(page){await page.evaluate(()=>{const {viewer}=window.__earthusV2;viewer.camera.cancelFlight?.();viewer.camera.setView({destination:Cesium.Cartesian3.fromDegrees(0,89.15,2_200_000),orientation:{heading:0,pitch:Cesium.Math.toRadians(-90),roll:0}});viewer.scene.requestRender()});await waitFor(page,()=>{const p=window.__earthusV2?.viewer?.camera?.positionCartographic;if(!p)return false;const lat=Cesium.Math.toDegrees(p.latitude),h=p.height;return lat>85&&h>1_700_000&&h<2_700_000},8000);await settleGlobe(page,{minimumMs:4500,maximumMs:11000})}
async function setAmbientEvidenceView(page){await page.evaluate(()=>{const {viewer,realEarth}=window.__earthusV2;realEarth.enterEarth();viewer.camera.cancelFlight?.();viewer.camera.setView({destination:Cesium.Cartesian3.fromDegrees(127,25,20_500_000),orientation:{heading:0,pitch:Cesium.Math.toRadians(-90),roll:0}});viewer.scene.requestRender()});await settleGlobe(page,{minimumMs:3500,maximumMs:9000})}

fs.mkdirSync(outputRoot,{recursive:true});const server=localServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});page.setDefaultTimeout(90000);const cdp=await page.context().newCDPSession(page);const pageErrors=[];page.on('pageerror',error=>pageErrors.push(String(error?.stack||error)));const consoleMessages=[];page.on('console',msg=>{if(['error','warning'].includes(msg.type()))consoleMessages.push({type:msg.type(),text:msg.text()})});const responses=[],requestFailures=[];page.on('response',response=>{const url=response.url();if(/gibs\.earthdata\.nasa\.gov|arcgisonline\.com|elevation3d\.arcgis\.com|\/clouds\//.test(url)||response.status()>=400)responses.push({status:response.status(),url})});page.on('requestfailed',request=>requestFailures.push({url:request.url(),error:request.failure()?.errorText||null}));const states={};
try{
 console.log('VISUAL STAGE earth');await page.goto(`http://127.0.0.1:${port}/v2/`,{waitUntil:'domcontentloaded',timeout:60000});await waitFor(page,()=>!!window.__earthusV2?.realEarth&&document.documentElement.dataset.c==='1',60000);await settleGlobe(page,{minimumMs:7000,maximumMs:18000});states.earth=await snapshot(page,cdp,'01-earth');assertSignal('earth',visualMetrics['01-earth'],{minMean:.025,minStd:.03,minRange:.09});assert.equal(states.earth.fallbackDisplay,'none','CSS fallback globe is still covering Cesium');assert.equal(states.earth.terrainTruth,'ESRI_TERRAIN3D','normal Earth must use flat-ocean Terrain3D surface');assert.equal(states.earth.bathymetryTruth,'ESRI_TOPOBATHY3D','TopoBathy provider must be ready for depth modes');assert.equal(states.earth.polarTruth,'NASA_GIBS_GEOGRAPHIC_POLAR_HOLE_FILL_IMAGERY_ONLY','geodetic polar hole-fill did not initialize');assert.equal(states.earth.polarSources.length,2,'both geodetic polar hole-fill sources are required');assert.ok(states.earth.polarSources.every(x=>x.truthClass==='NASA_GIBS_GEOGRAPHIC_IMAGERY_ONLY'&&Number(x.imageSignal?.mean)>.018),'polar imagery source signal gate failed');assert.match(states.earth.sourceBadge||'',/TERRAIN: Esri Terrain3D/);assert.match(states.earth.sourceBadge||'',/BATHY: Esri TopoBathy3D ready/);
 console.log('VISUAL STAGE polar');await setPolarView(page);states.polar=await snapshot(page,cdp,'01b-polar');assertSignal('polar',visualMetrics['01b-polar'],{minMean:.02,minStd:.025,minRange:.07});assertSignal('polar-center',visualMetrics['01b-polar-center'],{minMean:.025,minStd:.01,minRange:.025,maxDarkRatio:.45});assert.ok(states.polar.cameraLatitudeDeg>85);assert.equal(states.polar.polarTruth,'NASA_GIBS_GEOGRAPHIC_POLAR_HOLE_FILL_IMAGERY_ONLY');await setAmbientEvidenceView(page);
 console.log('VISUAL STAGE clouds');const cloudAttempt=await page.evaluate(async()=>{const manifestResponse=await fetch('/clouds/gk2a/cth/manifest.json',{cache:'no-cache'}),manifest=await manifestResponse.json();window.__earthusV2.realEarth.enterEarth();const result=await Promise.race([window.__earthusV2.realEarth.showBestCloud3d(),new Promise(resolve=>setTimeout(()=>resolve('CLIENT_TIMEOUT'),45000))]);return{status:manifestResponse.status,manifest,result,diagnostics:window.__earthusV2.realEarth.cloudDiagnostics?.()||null,fidelity:window.__earthusV2.realEarth.cloudFidelity?.()||null}});states.cloudAttempt=cloudAttempt;assert.equal(cloudAttempt.status,200);assert.equal(cloudAttempt.manifest.ready,true);assert.equal(cloudAttempt.manifest.synthetic,false);assert.equal(cloudAttempt.manifest.truthClass,'OBSERVED_DERIVED_OFFICIAL_L2');assert.equal(cloudAttempt.manifest.units,'m');assert.ok(['VOLUME','CTH_RELIEF'].includes(cloudAttempt.result),`3D cloud selection failed: ${JSON.stringify(cloudAttempt)}`);await waitFor(page,()=>['VOLUME','CTH_RELIEF'].includes(window.__earthusV2?.realEarth?.cloudFidelity?.()),10000);await waitFor(page,()=>{const h=window.__earthusV2?.viewer?.camera?.positionCartographic?.height,p=Cesium.Math.toDegrees(window.__earthusV2?.viewer?.camera?.pitch||0);return h>500000&&h<2600000&&p<-30},20000);await settleGlobe(page,{minimumMs:5000,maximumMs:14000});states.clouds=await snapshot(page,cdp,'02-clouds');assertSignal('clouds',visualMetrics['02-clouds'],{minMean:.03,minStd:.035,minRange:.1});assert.notEqual(states.clouds.cloudFidelity,'SHELL',`3D cloud fidelity fell back to shell: ${JSON.stringify(states.clouds.cloudDiagnostics)}`);
 console.log('VISUAL STAGE trench');await page.evaluate(()=>window.__earthusV2.requestFeature('OCEAN','Bathymetry / Trench'));await waitFor(page,()=>Number(window.__earthusV2?.realEarth?.trenchSample?.()?.depthM)>0,45000);await waitFor(page,()=>{const h=window.__earthusV2?.viewer?.camera?.positionCartographic?.height,p=Cesium.Math.toDegrees(window.__earthusV2?.viewer?.camera?.pitch||0);return h>20000&&h<200000&&p<-50},20000);await settleGlobe(page,{minimumMs:7000,maximumMs:18000});states.trench=await snapshot(page,cdp,'03-trench');assertSignal('trench',visualMetrics['03-trench'],{minMean:.025,minStd:.018,minRange:.055});assert.equal(states.trench.terrainTruth,'ESRI_TOPOBATHY3D','trench must switch to TopoBathy3D');assert.ok(states.trench.trenchSample?.depthM>0);assert.equal(states.trench.globeLighting,false);assert.equal(states.trench.skyPanoramaVisible,false);
 console.log('VISUAL STAGE underwater');await page.evaluate(()=>window.__earthusV2.requestFeature('OCEAN','Underwater'));await waitFor(page,()=>{const h=window.__earthusV2?.viewer?.camera?.positionCartographic?.height,p=Cesium.Math.toDegrees(window.__earthusV2?.viewer?.camera?.pitch||0);return h<-1000&&p<-60},45000);await settleGlobe(page,{minimumMs:9000,maximumMs:22000});states.underwater=await snapshot(page,cdp,'04-underwater');assertSignal('underwater',visualMetrics['04-underwater'],{minMean:.008,minStd:.006,minRange:.02});assert.equal(states.underwater.terrainTruth,'ESRI_TOPOBATHY3D');assert.ok(states.underwater.cameraHeight<-1000);assert.equal(states.underwater.translucencyEnabled,true);assert.equal(states.underwater.frontFaceAlpha,1);assert.equal(states.underwater.backFaceAlpha,1);assert.equal(states.underwater.skyPanoramaVisible,false);assert.equal(pageErrors.length,0,`page errors: ${pageErrors.join('\n')}`);
 fs.writeFileSync(path.join(outputRoot,'state.json'),JSON.stringify({ok:true,states,visualMetrics,pageErrors,consoleMessages,responses:responses.slice(-500),requestFailures:requestFailures.slice(-150)},null,2));console.log('V2 REAL LIVING EARTH BROWSER VISUAL: PASS');console.log(JSON.stringify({states,visualMetrics},null,2));
}catch(error){if(!states.failure)try{states.failure=await pageState(page)}catch(_){}fs.writeFileSync(path.join(outputRoot,'state.json'),JSON.stringify({ok:false,error:String(error?.stack||error),states,visualMetrics,pageErrors,consoleMessages,responses:responses.slice(-500),requestFailures:requestFailures.slice(-150)},null,2));try{const {data}=await cdp.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});fs.writeFileSync(path.join(outputRoot,'99-failure.png'),Buffer.from(data,'base64'))}catch(_){}throw error}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
