import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {PNG} from 'pngjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const prototypeRoot=path.join(root,'prototype');
const out=path.resolve(process.env.EARTHUS_V2_VISUAL_OUTPUT||path.join(root,'output/v2-real-living-earth-visual-readpixels'));
const moduleRef=process.env.EARTHUS_PLAYWRIGHT_MODULE;
const playwright=moduleRef?await import(pathToFileURL(path.resolve(moduleRef)).href):await import('playwright');
const {chromium}=playwright;
const CLOUD='https://earthus-cache-kr.s3.us-east-2.amazonaws.com';
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'};

function server(){return http.createServer(async(req,res)=>{let p;try{p=decodeURIComponent(new URL(req.url,'http://x').pathname)}catch{res.writeHead(400).end();return}if(p.startsWith('/clouds/')){try{const r=await fetch(CLOUD+p,{cache:'no-store'}),b=Buffer.from(await r.arrayBuffer());res.writeHead(r.status,{'Content-Type':r.headers.get('content-type')||'application/octet-stream','Access-Control-Allow-Origin':'*','Cache-Control':'no-store'}).end(b)}catch(e){res.writeHead(502).end(String(e))}return}if(p==='/'||p==='/v2'||p==='/v2/')p='/v2/index.html';const f=path.resolve(prototypeRoot,'.'+p);if(!f.startsWith(prototypeRoot+path.sep)){res.writeHead(403).end();return}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404).end();return}res.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'}).end(b)})})}
async function wait(page,fn,ms=45000){const end=Date.now()+ms;while(Date.now()<end){try{if(await page.evaluate(fn))return}catch{}await page.waitForTimeout(180)}throw new Error('READPIXELS_VISUAL_WAIT_TIMEOUT')}
async function settle(page,ms=2500){const end=Date.now()+ms;while(Date.now()<end){await page.evaluate(()=>window.__earthusV2?.viewer?.scene?.requestRender?.());await page.waitForTimeout(220)}}
function signal(buf,region={x0:.08,x1:.92,y0:.06,y1:.94}){const p=PNG.sync.read(buf),d=p.data,x0=Math.floor(p.width*region.x0),x1=Math.floor(p.width*region.x1),y0=Math.floor(p.height*region.y0),y1=Math.floor(p.height*region.y1),v=[];let sum=0,sum2=0,n=0,dark=0;for(let y=y0;y<y1;y+=2)for(let x=x0;x<x1;x+=2){const i=(y*p.width+x)*4,l=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/255;sum+=l;sum2+=l*l;n++;v.push(l);if(l<.02)dark++}v.sort((a,b)=>a-b);const mean=sum/n,std=Math.sqrt(Math.max(0,sum2/n-mean*mean)),p10=v[Math.floor(n*.1)]||0,p90=v[Math.floor(n*.9)]||0;return{width:p.width,height:p.height,mean:+mean.toFixed(5),std:+std.toFixed(5),range:+(p90-p10).toFixed(5),darkRatio:+(dark/n).toFixed(5)}}
function gate(name,m,{mean=.01,std=.01,range=.03,dark=.9}={}){assert.ok(m.mean>=mean,`${name}:mean:${m.mean}`);assert.ok(m.std>=std,`${name}:std:${m.std}`);assert.ok(m.range>=range,`${name}:range:${m.range}`);assert.ok(m.darkRatio<=dark,`${name}:dark:${m.darkRatio}`)}
async function state(page){return page.evaluate(()=>{const r=window.__earthusV2?.realEarth,v=window.__earthusV2?.viewer,p=v?.camera?.positionCartographic;return{terrain:r?.terrainTruth?.(),bathymetry:r?.bathymetryTruth?.(),polar:r?.polarTruth?.(),polarSources:r?.polarSources?.(),cloud:r?.cloudFidelity?.(),cloudDiagnostics:r?.cloudDiagnostics?.(),depth:r?.trenchSample?.(),height:p?.height??null,lat:p?Cesium.Math.toDegrees(p.latitude):null,pitch:v?Cesium.Math.toDegrees(v.camera.pitch):null,lighting:v?.scene?.globe?.enableLighting,translucency:v?.scene?.globe?.translucency?.enabled,front:v?.scene?.globe?.translucency?.frontFaceAlpha,back:v?.scene?.globe?.translucency?.backFaceAlpha,badge:document.getElementById('earthusV2RealSources')?.textContent||null}})}
async function capture(page,name,metrics){const data=await page.evaluate(()=>{const v=window.__earthusV2?.viewer;if(!v)throw new Error('CESIUM_VIEWER_MISSING');const scene=v.scene;scene.requestRender();scene.render();const gl=scene.context?._gl;if(!gl)throw new Error('CESIUM_GL_MISSING');const w=gl.drawingBufferWidth,h=gl.drawingBufferHeight;if(!(w>0&&h>0))throw new Error(`CESIUM_GL_SIZE:${w}x${h}`);const raw=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,raw);const flipped=new Uint8ClampedArray(raw.length),row=w*4;for(let y=0;y<h;y++)flipped.set(raw.subarray((h-1-y)*row,(h-y)*row),y*row);const cv=document.createElement('canvas');cv.width=w;cv.height=h;const cx=cv.getContext('2d');if(!cx)throw new Error('READPIXELS_2D_CONTEXT_MISSING');cx.putImageData(new ImageData(flipped,w,h),0,0);const u=cv.toDataURL('image/png');return u.slice(u.indexOf(',')+1)});const buf=Buffer.from(data,'base64');fs.writeFileSync(path.join(out,name+'.png'),buf);metrics[name]=signal(buf);if(name==='01b-polar')metrics[name+'-center']=signal(buf,{x0:.34,x1:.66,y0:.22,y1:.78});return state(page)}

fs.mkdirSync(out,{recursive:true});
const s=server();await new Promise(r=>s.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1280,height:800},deviceScaleFactor:1});page.setDefaultTimeout(70000);
const states={},metrics={},errors=[];page.on('pageerror',e=>errors.push(String(e)));
try{
 console.log('READPIXELS STAGE earth');await page.goto(`http://127.0.0.1:${s.address().port}/v2/`,{waitUntil:'domcontentloaded',timeout:60000});await wait(page,()=>document.documentElement.dataset.c==='1'&&!!window.__earthusV2?.realEarth,60000);await settle(page,4200);states.earth=await capture(page,'01-earth',metrics);gate('earth',metrics['01-earth'],{mean:.02,std:.025,range:.07,dark:.75});assert.equal(states.earth.terrain,'ESRI_TERRAIN3D');assert.equal(states.earth.bathymetry,'ESRI_TOPOBATHY3D');assert.equal(states.earth.polar,'NASA_GIBS_GEOGRAPHIC_POLAR_HOLE_FILL_IMAGERY_ONLY');assert.equal(states.earth.polarSources?.length,2);
 console.log('READPIXELS STAGE polar');await page.evaluate(()=>{const v=window.__earthusV2.viewer;v.camera.setView({destination:Cesium.Cartesian3.fromDegrees(0,89.15,2_200_000),orientation:{heading:0,pitch:Cesium.Math.toRadians(-90),roll:0}});v.scene.requestRender()});await settle(page,3500);states.polar=await capture(page,'01b-polar',metrics);gate('polar',metrics['01b-polar'],{mean:.02,std:.02,range:.06,dark:.75});gate('polar-center',metrics['01b-polar-center'],{mean:.025,std:.01,range:.025,dark:.45});
 console.log('READPIXELS STAGE clouds');await page.evaluate(()=>window.__earthusV2.realEarth.enterEarth());const ca=await page.evaluate(async()=>{const m=await (await fetch('/clouds/gk2a/cth/manifest.json',{cache:'no-cache'})).json(),result=await Promise.race([window.__earthusV2.realEarth.showBestCloud3d(),new Promise(r=>setTimeout(()=>r('CLIENT_TIMEOUT'),35000))]);return{m,result,diag:window.__earthusV2.realEarth.cloudDiagnostics()}});states.cloudAttempt=ca;assert.equal(ca.m.ready,true);assert.equal(ca.m.synthetic,false);assert.equal(ca.m.truthClass,'OBSERVED_DERIVED_OFFICIAL_L2');assert.ok(['VOLUME','CTH_RELIEF'].includes(ca.result),JSON.stringify(ca));await settle(page,3000);states.clouds=await capture(page,'02-clouds',metrics);gate('clouds',metrics['02-clouds'],{mean:.02,std:.025,range:.07,dark:.8});assert.notEqual(states.clouds.cloud,'SHELL',JSON.stringify(states.clouds.cloudDiagnostics));
 console.log('READPIXELS STAGE trench');await page.evaluate(()=>window.__earthusV2.realEarth.enterTrench());await wait(page,()=>Number(window.__earthusV2.realEarth.trenchSample?.()?.depthM)>0,40000);await settle(page,4000);states.trench=await capture(page,'03-trench',metrics);gate('trench',metrics['03-trench'],{mean:.015,std:.012,range:.035,dark:.85});assert.equal(states.trench.terrain,'ESRI_TOPOBATHY3D');assert.ok(states.trench.depth?.depthM>0);
 console.log('READPIXELS STAGE underwater');await page.evaluate(()=>window.__earthusV2.realEarth.enterUnderwater());await wait(page,()=>Number(window.__earthusV2.viewer.camera.positionCartographic.height)<-1000,40000);await settle(page,4500);states.underwater=await capture(page,'04-underwater',metrics);gate('underwater',metrics['04-underwater'],{mean:.004,std:.004,range:.012,dark:.95});assert.equal(states.underwater.terrain,'ESRI_TOPOBATHY3D');assert.ok(states.underwater.height<-1000);assert.equal(states.underwater.translucency,true);assert.equal(states.underwater.front,1);assert.equal(states.underwater.back,1);assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(path.join(out,'state.json'),JSON.stringify({ok:true,states,metrics,errors},null,2));console.log('V2 REAL LIVING EARTH READPIXELS VISUAL: PASS');
}catch(e){try{states.failure=await state(page)}catch{}fs.writeFileSync(path.join(out,'state.json'),JSON.stringify({ok:false,error:String(e?.stack||e),states,metrics,errors},null,2));throw e}finally{await browser.close();await new Promise(r=>s.close(r))}
