import fs from 'node:fs';
import path from 'node:path';
import {EarthusAppIntegrationV35} from '../core/APP_INTEGRATION_V35.mjs';
import {STATES} from '../../06_BUNDLED_DATA_PACKAGE/pleos_safety_v33/PLEOS_SAFETY_GATE_V33.mjs';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../..');
const d=path.join(root,'06_BUNDLED_DATA_PACKAGE');
const master=JSON.parse(fs.readFileSync(path.join(d,'spatial_v24/POI_MASTER.json'),'utf8'));
const index=JSON.parse(fs.readFileSync(path.join(d,'spatial_v24/SPATIAL_GRID_INDEX.json'),'utf8'));
const app=new EarthusAppIntegrationV35({poiMaster:master,spatialIndex:index,drivingStateProvider:()=>STATES.PARKED,repository:{getEnvironment:async()=>({weather:{temperature:21},observedAt:'2026-09-25T00:00:00Z'})}});
app.setMapState({bbox:[128.9,35.0,129.1,35.2],dock:'local',layers:['weather','ocean']});
const q=await app.queryLocalPois({bbox:[128.9,35.0,129.1,35.2]});
if(!Array.isArray(q.items)) throw new Error('local query failed');
if(!app.actionAllowed('reservation')) throw new Error('parked reservation should be allowed by safety layer');
const poi=q.items[0]||master[0];
const card=await app.selectPoi(poi);
if(!card?.id) throw new Error('place card integration failed');
const before=app.snapshot(); app.setMapState({dock:'weather'}); const after=app.snapshot();
if(before.selectedPoiId!==after.selectedPoiId || before.bbox.join(',')!==after.bbox.join(',')) throw new Error('map/POI state not persistent');
console.log(JSON.stringify({status:'PASS',localPois:q.items.length,selectedPoi:card.id,statePersistence:'PASS',repository:'INJECTED',safety:'V33'}));
